- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
_pos is an array of position so getpos is useless
> Mortar not spawn

- =BTC=co@22_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
Change FOB and Supplies for Sling load Arma 3 compatibility.
Add Fuel tank for refuel vehicule on battlefield.
Add ammo box for rearm player on battlefield.
> Logisticpoint

- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
Remove flat condition for  mounting FOB easily on battlefield.
> Remove Flat condition

- =BTC=co@22_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/common/task_patrol.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
- Add enemy boat patrol
- for SDV select diver
> Add enemy boat patrol

- =BTC=co@22_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/int/orders_give.sqf
https://github.com/Giallustio/HeartsAndMinds/issues/59
> Add : Civ traffic can be used as taxi by player

- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
FIX : Check if civ is awake to ask reputation
> UPDATE : ask reputation

- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
Spawn info interaction if civ is awake
> FIX : ask info to unconscious civ

- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
Update : https://github.com/Giallustio/HeartsAndMinds/pull/63
> UPDATE: Interrogate Prisoner

- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
Update : https://github.com/Giallustio/HeartsAndMinds/pull/36
- Add check if unit isinstablecondition
> UPDATE : Side medical assistance

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_load.sqf
see https://github.com/Giallustio/HeartsAndMinds/pull/101
> DB FIX: objects loaded in cargo are missing after server restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_load.sqf
Reverts Vdauphin/HeartsAndMinds#92
> Revert "DB FIX: objects loaded in cargo are missing after server restart"

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/119
new rtp : [arma3server_2016-05-12_01-25-36.txt](https://github.com/Vdauphin/HeartsAndMinds/files/260394/arma3server_2016-05-12_01-25-36.txt) cleaner
Final test :
> FIX: building waypoint

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/paradrop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_unload.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unload.sqf
> FIX: paradrop issues

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
> FIX: vehicle flying when towing

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/obj_fall.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_unload.sqf
> FIX: objt fall explosion and findemptyposition error

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
> Add: spawn city radius in mission parameter

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
> FIX: lifting for unknown heli

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
>  	FIX: doc typo

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
FIX: wrong class name for RHS vehicle.
Final test :
> FIX: RHS class name

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/CuratorObjectPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/108
https://github.com/Giallustio/HeartsAndMinds/issues/99
Final test :
> FIX: Logistic spawned by curator not persistant

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
> FIX: start medical side when player is close enough

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/deleteTestObj.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
Julius need some info for this side mission ...
Final test :
> Add: smoke for checkpoint side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/deleteTestObj.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
https://community.bistudio.com/wiki/deleteVehicle
Final test :
> FIX: remove smoke effect correctly

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
> FIX: boat spawn on bridge

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_rinf.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
> FIX: Airport detection

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
> FIX: IA spawning in container

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_rinf.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
> FIX: unhook in ground

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
> Add: enemy can use civil vehicle for patrol

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/111
Final test :
> Add: Static Rearm box in Logistic Point menu

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
> FIX: AI do not respawn at correct place in house after city desactivation

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
FIX: missing documentation about rearming.
https://github.com/Vdauphin/HeartsAndMinds/issues/163
Final test :
> FIX: missing doc about rearming

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
FIX: Open Arsenal with ACE3 crash the game
Final test :
> FIX: Open Arsenal with ACE3 crash the game

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/148
Final test :
> Add: Syndikat, civ faction and vehicules

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
FIX: Now civilian are not spawning inside closed building.
FIX: Now enemies spawn less inside rock.
You can see 2 civilians and 1 enemy unit patrolling on the roof of a closed building.
Final test :
> FIX : AI spawn in closed building or rock

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
FIX: suicider sound hear by all player.
- change getpos for getposasl has explained in BI forum
- simplify get _suicider variable
Final test :
> FIX: suicider sound hear by all player

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh.sqf
`v= allMissionObjects "car"; count v;`
Final test :
> FIX: sometimes civ traffic spawn empty

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
see https://github.com/Vdauphin/HeartsAndMinds/pull/167
Final test :
> FIX: somtimes enemy patrol vehicule spawn empty

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
> FIX: debug output with H&M lifting

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
> FIX: suicider killed play allahu akbar

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
bug introduce by https://github.com/Vdauphin/HeartsAndMinds/pull/170
Final test :
> FIX: suicider explosion

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
ied check say some object spawned are ied when there are not.
Final test :
> FIX: ied check give wrong info

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
https://github.com/Vdauphin/HeartsAndMinds/pull/183
Final test :
> FIX: dirt road error for sidemission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/181
Final test :
> FIX: remove "ACE_friesAnchorBar"

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/marker_debug.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> Add: new debug system faster

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
Add: New side mission where you need to Rescue a helicopter pilot.
Final test :
> Add new Side mission : rescue pilot

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/CuratorCivPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/CuratorMilPlaced_s.sqf
Add: Set skill to IA spawning by curator.
https://github.com/Vdauphin/HeartsAndMinds/issues/160
Final test :
> Add: Curator setskill to civ and enemy

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
FIX: wrong DadtaBase version loading
Final test :
> FIX: database version loading

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
FIX: Now player connection is a little faster.
Final test :
> FIX: logistic delay at player connection

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/add_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
Add: improve side mission mine field with patrol and random type of mine.
Final test :
> Add: patrol for mine field side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
Add: Improve existing documentation with picture.
https://community.bistudio.com/wiki/Arma_3_Tasks_Overhaul
https://forums.bistudio.com/topic/175150-flag-picture-path/#post2814767
`"diag_log (getText (_x >> 'icon'));true" configClasses (configfile >> "CfgMarkers");`
`_imag  = "<img image='\a3\Ui_f\data\GUI\Cfg\CommunicationMenu\defend_ca.paa' align='center'/>"; 
_text = "<t color='#ff0000' size='1.2' shadow='1' shadowColor='#000000' align='center'>W</t><br/><br/>"; 
hint parseText (_imag + _text);`
Final test :
> Add: improve documentation design

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
FIX: Some IED can be check twice.
@Breech99
https://github.com/Vdauphin/HeartsAndMinds/issues/195
Final test :
> FIX: duplicate class name of IED

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/unit_killed.sqf
FIX: No reputation bonus when enemy killed.
https://github.com/acemod/ACE3/issues/3790
Final test :
> FIX: killed EH boken

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/add_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
FIX: Now when you heal with ACE3 a civilian, you get a reputation bonus.
https://github.com/acemod/ACE3/issues/4372
Final test :
> FIX: civilian healing

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
> FIX: unclear radius information

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> FIX: CUP vehicle can't be selected

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf
> FIX: playsound3D wrong parameter

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_damage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
FIX: Side mission healing civilians trow errors (link to ACE 3.7.0).
https://github.com/Vdauphin/HeartsAndMinds/issues/217
for side healing civilians after ACE3.7.0 released
Final test :
> FIX: side mission healing civilians

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
> Add: fastroping on helicopter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/spawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/179
Final test :
> Add: systemchat

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
> Add: now composition return objects created

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> Add: more IED class name

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/spawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_attachto.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/189
Final test :
`_getlock = getnumber (configfile >> "CfgWeapons" >> _cfgName >> "canLock");`
> Add: random cache design

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
https://forums.bistudio.com/topic/165948-mp-btc-hearts-and-minds/?p=3103071
Final test :
> FIX: unclear side description

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: AI position is not show sometimes in debug 

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> FIX: syntaxe error for Tanoa vehicle classname

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
> FIX: No FOBs deployed hint

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
you are not suppose to load in anything in a static
Final test :
> FIX : remove check cargo/load selected on static objects

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
> FIX: Convoy side mission status

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
> FIX: task say the convoy is attacking the wrong city

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_eh.sqf
- README.md
> FIX: Group created by fnc_traffic/patrol are not deleted

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/unit_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
> Add: icon to ACE3 interaction menu

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud.sqf
- FIX: sometimes when ACE3 FRIES is activate you can't lift with some helicopter.
Final test :
> FIX: sometimes when ACE3 FRIES is activate you can't lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/rsc.hpp
https://github.com/Vdauphin/HeartsAndMinds/issues/249
- FIX: Now H&M lift HUD is circle.
Final test :
> FIX: HUD lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
https://forums.bistudio.com/topic/165948-mp-btc-hearts-and-minds/?p=3103685
Final test :
> Add: BIS group 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
> FIX: tower should spawn on road to avoid collision

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/258
Final test :
before
after
> FIX: Wreck Respawn, Vehicles respawn half way in ground

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
FIX: Side mission medical is not trigger when multiple player are connected on server.
Final test :
> FIX: side mission medical is not trigger correctly

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/obj_fall.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/paradrop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_unload.sqf
FIX: Objects unload fall under bridge.
Final test :
> FIX: object unload fall under bridge

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
bug introduce by : https://github.com/Vdauphin/HeartsAndMinds/pull/175
Final test :
> RMV: fasteroping on "RHS_UH1Y_d" due to bad visual effect

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/autosave.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/autosave.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/220
https://forums.bistudio.com/topic/165948-mp-btc-hearts-and-minds/?p=3105658
Final test :
> Add: Auto Save Game

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/189
Final test :
> Add: composition for Side tower 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/tasktypes.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
https://github.com/Vdauphin/HeartsAndMinds/issues/188
Final test :
> Add: Icon to task

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
now when you are inside a vehicle check cargo is available by
interacting with the vehicle
Final test :
> Add: Now check cargo is inside vehicle

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/274
Final test :
> FIX: Typo spelling error on final task

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/obj_fall.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/paradrop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_unload.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- README.md
this will attach rope at the correct position on vehicle if available
Final test :
> Add: Sling load visual improvement

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
> Add: ACE3 action for lifting is now on helicopter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
> Add: Better heavy lift support

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
merge this before https://github.com/Vdauphin/HeartsAndMinds/pull/214
I don't see any difference between `setPosASL` and `setPosATL` (in spawn accuracy)
Final test :
> FIX: vehicle not spawning on bridge after DB save

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
FIX: Sometimes rope is not long enough for lifting.
https://youtu.be/vM2tOa6JfzA?t=1184
RIP Burke.
Now it is : 
Final test :
> FIX: Sometimes rope is not long enough for lifting

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/deaf/earringing.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf
FIX: Ringing noise not compatible with ACE3 ear plugs.
https://github.com/Vdauphin/HeartsAndMinds/issues/221
Final test :
> FIX: Ringing noise not compatible with ACE3

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> FIX: rescue pilot kill by ACE cookoff

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
FIX: Get down order to civil.
Final test :
> FIX: get down order to civil

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
FIX: When an underground object is unhook on bridge, it fall under it.
Final test :
> FIX: better support of bridge during unhook

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
most of the time the traffic/Patrol fail to find a correct city when
there are on an island (Tanoa). This should improved that point.
Final test :
> FIX: Traffic/Patrol on island

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
FIX: Cache is not spawning in final phase.
Final test :
> FIX: Cache don't spawn in final phase

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/add_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/firednear.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/remove_eh.sqf
> Add: Civilan fleeing

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
FIX: When a player vehicles is destroyed the malus is a bonus.
FIX: If a player vehicle  is destroyed twice the malus is not apply after.
Final test :
> FIX: reputation malus on vehicles is not apply.

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> FIX: Duplicate static magazine

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/add_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
Mil send are not in HC and Clean btc_fnc_data_add_group
Final test :
> FIX: Mil send are not in HC

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
FIX: Hideouts are not capturing cities around after a delay.
Final test :
> FIX: Hideout capture city around

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
> Add: Optimize Add_actions for civil orders

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
> Add: Side mission cycle

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
> FIX:  Missing interaction icon on StaticWeapon.

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
FIX: Player don't get any notification when side mission convoy and capture an officier begin.
Final test :
> FIX: notification for convoy side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
most of the time vehicle fly or are in the ground when the towing
fearture is activating
Final test :
> FIX: Vehicles fly or are in the ground during towing

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/can_tow.sqf
FIX: car can tow truck or tank
FIX: tank can't be lift
FIX: tank can't be tow by truck or tank
Final test :
> FIX: Classe name in towing system

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/extended_InitPost_EH.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud_loop.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/176
Somtimes object fall in sea. The SDV allow us to find and lift this object under water.
Final test :
> Add: Lift underwater

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
FIX: DO NOT rotate while your are walking near an IED: prefer walk, stop, rotate, walk again etc
Final test :
> FIX: documentation for IED disarming

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
> FIX: Check cap error

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/task_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
sometimes waypoints patrol are out of radius of city
Final test :
> FIX: Patrol area

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
FIX: When player fall unconscious, AI disappear.
Need Arma 3 1.67
Final test :
> FIX: when player is civilian (unconscious), trigger are not activated

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
Add: Units close to the generator in the Side mission.
Final test :
> Add: Units close to the generator in the Side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
> FIX: group created are not delete in some case

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook_fake.sqf
FIX: Wreck lift.
Avoid this https://github.com/Vdauphin/HeartsAndMinds/issues/307
Final test :
> FIX: Wreck lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
> FIX: btc_fnc_mil_send for headless

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/326
FIX: Defuse IED don't give reputation to player
Final test :
> FIX: Defuse IED don't give reputation to player

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh.sqf
when a car hit an object, it is immediately remove even if the car has
nothing broken.
Final test :
> FIX: Traffic is removed too quick

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_change_target.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/325
Final test :
> Add: Empty Ammo Crates from Logistics Crate

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
> Add: btc_fnc_city_create for city\init.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/action_result.sqf
> FIX: Body above water are not searchable (bridge)

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
> FIX: player spawn under the FOB floor

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create.sqf
> FIX: can't use logistic point when animals or module are placed on

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/can_tow.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/hook.sqf
> FIX: doc about towing

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/234
Final test :
Before restart:
After restart (WITHOUT the FIX):
And After restart (WITH the FIX):
Nothing moved!!!
> FIX: DataBase vehicles are damaged when loaded

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
> Add: Civil give the number of hideouts left

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place_create_camera.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place_destroy_camera.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
> Add: New side mission hack a missile

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/fired_near.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/235
Final test :
> Add: CBA Per Frame Handlers for btc_fnc_delete/iedcheck/suicider

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dismantle_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
https://forums.bistudio.com/forums/topic/165948-mp-btc-hearts-and-minds/?page=28#comment-3189366
Final test :
> FIX: Helo and logistic point elevation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: player respawn at connection position 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
> FIX: Civilian/Enemies mouvement in house

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_change_target.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
> Add: Dynamic logistic point

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- Add: Optimize mission parameters.
Param.hpp changed
Final test :
> Add: New mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook_fake.sqf
> FIX: Hide the box use during wreck lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/create.sqf
> FIX: IED appear in front of player in some cases

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
FIX: Side mission Hostage fail for no reason.
Final test :
> FIX: Side mission Hostage

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/372
Final test :
> FIX: Destroyed vehicle markers not appearing on dedicated server after a server restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
> FIX: Vehicle explosion damage other objects around during database loading

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create.sqf
> FIX: Weapon holder can block logistic point

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
> FIX: Can't combine faction from different side

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
https://github.com/Vdauphin/HeartsAndMinds/pull/144
Final test :
before
after
> FIX: Detect more accuratly city center in some cases

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
> FIX: Foot patrol can spawn inside rock

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
> FIX: Units in house are not saved correctly

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
https://github.com/Vdauphin/HeartsAndMinds/pull/263
Final test :
> FIX: side mission mine is not trigger correctly

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
> Add: Use pplinenumbers

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- Add: H&M do not overwrite ACE setting from mission.sqm module or others.
Final test :
> Add: Default value from ACE for mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
> FIX: Use black taru pod instead

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud_loop.sqf
> FIX: Remove fastrope from the lifting detection

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
> FIX: civilian suicider not killed due to pavement

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/copy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/paste.sqf
> Add: Copy/Paste tool for container

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/obj_fall.sqf
> FIX: Object flipping when touching the ground

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/396
https://forums.bistudio.com/forums/topic/207741-clients-see-different-colours-for-same-car/
Final test :
> FIX: Clients see different colours for same car

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
> FIX: Wreck vehicle malus is apply at each DB loading

- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_Tanoa.sqm
- Mission.sqm CHANGED
- FIX: RHS vehicles are underground since RHS 0.4.3 update.
Final test :
> FIX: RHS vehicles are underground

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
https://github.com/Vdauphin/HeartsAndMinds/issues/403
Final test :
> FIX: Tweak name Anti-Air infantry in param.hpp

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
> FIX: Grammar

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
> FIX: Broken Icon path for loading action

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
FIX: Helo is not respawning when destroyed on the helo spawn position.
Final test :
> FIX: Helo is not respawning when destroyed on the helo spawn position

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/getRearmMagazines.sqf
- use a dedicate fnc from ACE ? (a Vanilla `magazinesAmmoFull` but it does not find chaff for exemple)
Final test :
> FIX: Rearm

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_give.sqf
@cptnnick
```
for "_i" from 1 to 1000 do {
private _dir = 300;
private _amp = 40;
private _pos = (getpos player) getPos [100*sqrt random 1 , _dir -
0.5*_amp + random _amp];
deleteMarker str(_i);
private _marker = createmarker [str(_i), _pos];
systemChat str(_pos);
str(_i) setMarkerSize [1,1];
str(_i) setMarkerType "mil_dot";
str(_i) setMarkerColor "ColorBlue";
str(_i) setMarkerShape "ICON";
};
```
Final test :
> Add: Go away order is now directional

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/can_tow.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/get_corner_points.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/hitch_points.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
https://github.com/Vdauphin/HeartsAndMinds/pull/370
Final test :
> Add: Two ropes during towing

- README.md
> FIX: Readme.md

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add missing preprocessFileLineNumbers
- `preprocessFileLineNumbers`
- https://community.bistudio.com/wiki/Code_Optimisation#Preprocessfilelinenumbers
> Add: missing preprocessFileLineNumbers

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- FIX: Selectrandom in troops.sqf
> FIX: Selectrandom in troops.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- FIX: Civilian always say the truth for hideout and troops information
> FIX: Civilian always say the truth for hideout and troops information

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
fixed some more spelling/grammar.
test, test I do not know what I am doing but hopefully this is easier for you to implement than my previous issues report ;)
- Describe what this pull request will do
- Each change in a separate line
- Include documentation if applicable
- Choose the correct branch by reading [this](https://github.com/Vdauphin/HeartsAndMinds/wiki/For-developer-and-tester#branches)
> FIX: doc.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- btc_fnc_mil_create_group return an array now (same https://github.com/Vdauphin/HeartsAndMinds/pull/429)
> FIX: btc_fnc_mil_create_group return an array

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- FIX syntaxe error `setWaypointType "GET OUT";`
> FIX: Syntaxe error for setWaypointType

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- Add: Specific Icon to order action for a more intuitive selection.
> Add: Specific Icon to order action

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/remove_eh.sqf
- Fix rtp error when EH are removed twice on a civilian
> FIX: RTP errors when EH are removed twice

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/task_patrol.sqf
- The last waypoint for divers is now close to a location so player can see them easily
> FIX: Diver don't have waypoint on ground

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- add in documentation the database also save the camp channel
> FIX: Database also save camp channel

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- Replace the red container for supply side mission by the IDAP container.
> Add: IDAP containers for supply side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- Clean up misison.sqf
- remove some filter for class name
- reduce conflicts between branch due to verisoning
- clean up extrat (), tweaks comments, remove space for tabulation
- clean up  `btc_fnc_log_get_liftable`
> Add: Clean up mission.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Clean up English from stringtable because it is handle by original (https://github.com/Vdauphin/HeartsAndMinds/issues/400)
> Add: Clean up English from stringtable

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_damage.sqf
- FIX: Set damage fonction for side mission civilian treatment
- player have more time to heal the patient.
> FIX: Set damage fnc for side mission civilian treatment

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/get_corner_points.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- FIX: Lift behavior for helicopter wreck (@Vdauphin).
- first reference : https://github.com/Vdauphin/HeartsAndMinds/pull/477
- When helicopter wreck are lifted they flip without control.
> FIX: When helicopter wreck are lifted they flip without control

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: ACE Arsenal (@Vdauphin).
- Add: ACE Arsenal 
> Add: ACE Arsenal

- .github/PULL_REQUEST_TEMPLATE.md
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook_fake.sqf
- Add: Improve code with `params` and `private` (@Vdauphin).
- because the issue occure also in master_stable this has been migrated to master_stable
- Improve code with `params` and `private` 
> Add: Improve code with `params` and `private` for fnc_lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/suicider.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- FIX: City has no more suicider/drone (@Vdauphin).
- Now when suicider/drone is killed, the variable `has_suicider` is correctly set to false.
> FIX: Now when suicider/drone is killed, the variable `has_suicider` is set to false

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/garage.sqf
- FIX: Vehicle customization is not persistant (@Vdauphin).
- Save in database the customization of eatch vehicle and the garage spawn the vehicle with the choosed customization
> FIX: vehicle customization is not persistant

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- add space for message `Saving in progress... Please wait`
> FIX: Tweak space

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/showSubtitle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- Add: CBA_fnc_waitAndExecute convertion for H&M subtitles conversations (@1kuemmel1).
- replace `sleep `with `CBA_fnc_waitAndExecute` and `spawn `with `call` in all "subtitle-related" files (from #484 ). To better match with the [ACE3 General Rules](https://ace3mod.com/wiki/development/arma-3-scheduler-and-our-practices.html#32-ace3-general-rules)
> Add: Update for #484 (Subtitles for conversations)

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/spawn.sqf
- Change: Clean up weapon cache functions (@bux)
> Clean up cache functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- Change: Clean up city functions (@bux)
> Clean up city functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/CuratorCivPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_drone.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_leaflets.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/evacuate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh_remove.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/unit_create.sqf
- Change: Clean up civ functions (@bux)
> Clean up "civ" functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- Same as https://github.com/Vdauphin/HeartsAndMinds/pull/501 (@Vdauphin).
- compile fnc from  `addWP` to player locality.
> FIX: Missing functions on client

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- FIX: Vehicule customiazation for repair wrecks and respawn fonction (@Vdauphin).
- take advantage of `BIS_fnc_getVehicleCustomization` to add correct apparence to vehicle.
> FIX: Vehicle customization for repair wrecks and respawn fonction

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- FIX: Side mission for join in process player (@Vdauphin).
- After side mission ceation, JIP player don't see the task on the map
- This add JIP for side mission
- This issue is link to the task localisation (https://github.com/Vdauphin/HeartsAndMinds/pull/427). A rewrite on this part of the mission is necessary for a more simple and effective task management.
> FIX: Side mission JIP

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/deaf/earringing.sqf
- Change: Clean up deaf functions (@Vdauphin).
> Clean up deaf functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/add_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- Change: Clean up data functions (@Vdauphin).
> Clean up data functions

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Add guilines for H&M in github pull request template
> FIX: guidelines missing in PR template

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
- Ignore changlog
- Use setVariable in remoteExec
> FIX: btc_fnc_int_change_var no more used

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dismantle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dismantle_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dlg.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/lb_change.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- Change: Clean up eh functions (@Vdauphin).
> Clean up fob functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/belt.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_fire.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effect_blurEffect.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effect_color_smoke.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effect_rocks.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effect_shock_wave.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effect_smoke.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/fired_near.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/ied_effects.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/init_area.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- Change: Clean up ied functions (@Vdauphin).
> Clean up ied functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/give_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/has_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/search_for_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- Change: Clean up info functions (@Vdauphin).
> Clean up info functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/action_result.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ans_var.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_give.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/shortcuts.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/terminal.sqf
- Change: Clean up int functions (@Vdauphin).
> Clean up int functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/CuratorMilPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/add_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/aiskill.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/getStructures.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_eh_remove.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/set_skill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/unit_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/unit_killed.sqf
- Change: Clean up mil functions (@Vdauphin).
> Clean up mil functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
- Change: Clean up task functions (@Vdauphin).
> Clean up task functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/add_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/eh_effects.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/firednear.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/remove_eh.sqf
- Change: Clean up rep functions (@Vdauphin).
> Clean up rep functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/check_los.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_attachto.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/deleteTestObj.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/deletegroup.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/end_mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_veh_with_turret.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/findposoutsiderock.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/findsafepos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_cardinal.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_owners.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/intro.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/marker_debug.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/randomize_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/road_direction.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_damage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_groupowner.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_markerTextLocal.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_owner.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/showSubtitle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/systemchat_debug.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/task_patrol.sqf
- Change: Clean up common functions (@Vdauphin).
> Clean up common functions 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- Change: Clean up city functions (@Vdauphin).
> Clean up city functions 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_attachto.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_owner.sqf
- Add: Clean up set_owner file (@Vdauphin).
- Clean up set_owner file
> Clean up set_owner file

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_headless.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- =BTC=co@30_Hearts_and_Minds.Altis/init.sqf
- Change: Clean up core functions (@Vdauphin).
> Clean up core functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- Add: in command (@Vdauphin).
- Use `in` command for multiple test
> Add: in command

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/give_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout.sqf
- ignore change log (@Vdauphin).
- wrong exitwith condition since : https://github.com/Vdauphin/HeartsAndMinds/pull/529
> FIX: Hideout intel

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- Add: Simplify respawn (@Vdauphin).
- Remove global variable for respawn
> Add: Simplify respawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- Add: Use function btc_fnc_mil_create_hideout for data base loading (@Vdauphin).
- Now data base loading for hideout are done by the `btc_fnc_mil_create_hideout` function
> Add: data base loading in function btc_fnc_mil_create_hideout

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- btc_fnc_delete take only 3 parameters
> FIX: Hostage side is not clean up when abort or failed

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
- `distance` does not take array of objects 
> FIX: ask_var function for hideouts

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- FIX: Remove patrol on foot (@Vdauphin).
- Also remove patrol on foot
> FIX: Remove patrol on foot

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_eh.sqf
- Add: Enhanced patrol eh fnc (@Vdauphin).
- btc_fnc_mil_patrol_eh can remove foot patrol
- and also vehicle patrol
> Add: Enhanced btc_fnc_mil_patrol_eh

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- Add: Use the btc_fnc_foc_create_s to load FOB from DB (@Vdauphin).
- Use the btc_fnc_foc_create_s to load FOB from DB
> Add: Use the fnc create_s to load FOB from DB

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- FIX: AI is healing him self in side mission treatment (@Vdauphin).
- AI is healing him self in side mission treatment
- increase the treatmentOverAt variable https://github.com/acemod/ACE3/blob/master/addons/medical_ai/functions/fnc_healSelf.sqf#L22-L23 used to exitwith the healing self ACE function
> FIX: AI is healing him self in side mission treatment

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- Syntax error _veh_type is undefine
> FIX: syntaxe error where _veh_type is undefine

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
- Add: Sniper and Machine gunner autoloadout (@Vdauphin).
- add sniper
- add MG 
- testing code:
```sqf
[] spawn {
{
private _i = _x;
{
private _j = _x;
{
player setUnitLoadout ([_i, _j, _x] call btc_fnc_arsenal_loadout);
sleep 1;
} foreach [false,true];
} foreach [0,1,2];
} foreach [0,1,2,3,4,5,6,7,8];
};
```
> Add: Sniper and Machine gunner in autoloadout

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- FIX: Checkpoint are too far from the city center (@Vdauphin).
- use city radius to determine the correct radius to search for road
> FIX: Checkpoint are too far from the city center

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- Add: Direction to mil_createVehicle function (@Vdauphin).
- create static function use mil createVehicle
- mil createVehicle support a new parameter : direction
> Add: dir in function createvehicle and update create_static

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_RHSUS_Altis.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_RHSUS_Tanoa.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: New slots and autoloadout in mission parameters (@Vdauphin).
- mission.sqm changed
- param.hpp changed
- add autoloadout in mission parameters
- add new slots
> Add: New slots and autoloadout in mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dlg.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/lb_change.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Clean up redeploy (@Vdauphin).
- remove string in stringtable no more used
- remove dialog for the old reploy map
- https://github.com/Vdauphin/HeartsAndMinds/pull/238
> Add: Clean up redeploy

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_RHSUS_Altis.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_RHSUS_Tanoa.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Use stringtable from BIS (@Vdauphin).
- use stringtable from BIS
> Add: Use stringtable from BIS

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
- Add: Improve filter class name (@Vdauphin).
- use config entry to filter more accurately class names.
> Add: Improve filter class name 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- Add: Remove btc patrol variable (@Vdauphin).
-  Remove `btc patrol` variable because it is unused
> Add: Remove btc patrol variable

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- Add: Improve the btc_fnc_mil_create_group function (@Vdauphin).
- Clean up and restructure the function
> Add: Improve the create_group function

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/findPos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createUnits.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/getBuilding.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- Add: Improve the global system of create_group (@Vdauphin).
- simplify create group function
- split into functions
- use int instead of float for number of groups and units
> Add: Improve the global system of create_group

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: Mortar entry "B_Mortar_01_F" (@Vdauphin).
-  remove "B_Mortar_01_F"  
> FIX: Mortar entry "B_Mortar_01_F"

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
> FIX: Backward compatiblity with 1.18

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/ammoUsage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/data.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/garage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/trait.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/weaponsfilter.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- add header to arsenal functions
> Add: Header to Arsenal functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- FIX: Bodies are deleted too close from players (@Vdauphin).
- increase the distance from the player
- Fixes #583
> FIX: Bodies are deleted too close from players

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create_attachto.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/spawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- add header to cache functions.
> Add: Header to cache functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/findPos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/CuratorCivPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_leaflets.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/evacuate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/unit_create.sqf
> Add: Header to city and civ

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Portuguese in stringtable.xml  (@EckoMoire).
- Just added the <Portuguese> with translations to all strings
> Updated the stringtable.xml with <Portuguese>

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/debug/graph.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effects.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
> FIX: Move comment in header

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/randomize_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/showSubtitle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/buildingchanged.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place_key_down.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createUnits.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/WPCheck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/usefulCity.sqf
- tools/add_header.py
> FIX: wrong syntaxe in header: boolean

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_deploy_ropes.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- ignore changlog
- remove duplicate
> Clean up redondent string

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/WPCheck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/init.sqf
- Ignore changelog
- fix boat flip up and down
- vehicle stuck when they reach the last waypoint randomly
- vehicle spawn on tiny road of tanoa
- use `assigned` to remove the vehicle when the civilian move out of his vehicle
> FIX: Patrol system

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- FIX: Hideout spotted with info is different between save (@Vdauphin).
- error, id is not the position in the array 
> FIX: Hideout spotted with info is different between save

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/check_los.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/end_mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_veh_with_turret.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/findposoutsiderock.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/findsafepos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_cardinal.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/intro.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/randomize_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/road_direction.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_damage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_groupowner.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_groupsowner.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_markerTextLocal.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/showSubtitle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/strategicMapOpen.sqf
> Add: Missing header

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: Wrong Comments btc_type_gl (@Vdauphin).
- fix #635
> FIX: Wrong Comments btc_type_gl

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- Add: get composition function (@Vdauphin ).
- this function allow to get composition of objects and can be created by the create composition function already available.
> Add: get composition function

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/FOB_killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- Add: Remove FOB when FOB structure is destroyed (@Vdauphin).
- Remove FOB when there are destroyed.
~~- [ ] remove FOB_name, use marker and then markerText~~
> Add: Remove FOB when FOB structure is destroyed

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_apply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: food and water supply for side mission supply (@Vdauphin).
- Now to complet the mission you need to deliver food and water.
**Screenshot**
> Add: Improve supply mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/trait.sqf
- Add: Remove the parameter Medic Advanced to a global one based on ACE Medical setting (@Vdauphin).
- Remove the parameter Medic Advanced to a global one based on ACE Medical setting
> Remove the parameter Medic Advanced to a gobal one based on ACE Medical setting

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- FIX: Missing ACE3 parameters for Helo (@Vdauphin).
- Now also Helo has ACE3 parameters
- fix #654 
> FIX: Missing ACE3 parameters for Helo

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- FIX: case selection for static spawn (@1kuemmel1)
- simply adjust the conditions for the cases
> FIX: Case conditions for static spawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/handledisconnect.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/suicider.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/belt.sqf
- Add: Add: Header comments to functions (@Vdauphin).
- add header functions
> Add: Header comments to functions

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/dlg.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- Add: Improve code syntaxe (@Vdauphin).
- slightly improve code syntaxe 
> Add: Improve code syntaxe

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Disable wreck system on Helo vehicles (@Vdauphin).
- title
> FIX: Disable wreck system on Helo vehicles

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- Add: FOB spawn in the same direction as the container (@Vdauphin).
- Now FOB will no more only in North direction but accordingly to the container orientation
> Add: Direction to FOB

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/setCargo.sqf
- Add: setCargo fnc (@Vdauphin).
- title
> Add: setCargo fnc

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/CuratorCivPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/unit_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/CuratorMilPlaced_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createUnits.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/unit_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- Add: Use group param for fncs unit_create (@Vdauphin).
- btc_fnc_mil_unit_create take group parameter 
- btc_fnc_civ_unit_create use group param
> Add: Use group param for fncs unit_create

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: _cfgVehicles isn't defined (@Vdauphin).
- title
> FIX: _cfgVehicles isn't defined

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/trait.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create_attachto.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
- Add: Randomize time between cache explosion (@Vdauphin).
- title
> Add: Randomize time between cache explosion

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Save interaction, use scheduled (@Vdauphin).
- title
> FIX: Save interaction, use scheduled

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Logistic stringtable cleanup and migrate fnc to client/server (@Vdauphin).
- title
> Add: Logistic stringtable cleanup and migrate fnc to client/server

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- Add: Don't show database deleted when saving (@Vdauphin).
- title
> Add: Don't show database deleted when saving

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Side mission rescue, missing smoke (@Vdauphin).
- title
> FIX: Side mission rescue, missing smoke

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/end_mission.sqf
- FIX: Hint not show at mission end (@Vdauphin).
- title
> FIX: Hint not show at mission end

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/garage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/end_mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dismantle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/copy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/paste.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: CBA_fnc_notify instead of hint (@Vdauphin).
- title
- remove comment as there are in stringtable but keep those in mission parameters to easier reading
> Add: CBA_fnc_notify instead of hint

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/garage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/checkArea.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/paste.sqf
- Add: Check area fncg (@Vdauphin).
- title
> Add: Check area fnc

- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- FIX: Disable BI wreck system to prevent conflict with H&M (@Vdauphin).
- title
- close #665 
> FIX: Disable BI wreck system to prevent conflict with H&M

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Delete action to logistic point (@Vdauphin).
- close #666 
> Add: Delete action to logistic point

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Pilot from rescue side mission not delete (@Vdauphin).
- title
> FIX: Pilot from rescue side mission not delete

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: Switch to OPF_G_F (@Vdauphin).
- title
> FIX: Switch to OPF_G_F

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- FIX: Floating compositions (@Vdauphin).
- title
> FIX: Floating compositions

- =BTC=co@30_Hearts_and_Minds.Altis/core/sounds/sounds.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- Add: Remove sounds.hpp (@Vdauphin).
- title 
> Add: Remove sounds.hpp

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- FIX: Missing private (@Vdauphin).
- title
> FIX: Missing private

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- Add: "CBA_NamespaceDummy" for city location (@Vdauphin).
- title
> Add: "CBA_NamespaceDummy" for city location

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
- Add: Improve entities syntax (@Vdauphin).
- title
> Add: Improve entities syntax

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/deaf/earringing.sqf
- Add: Don't get owner for earringing (@Vdauphin).
- title
> Add: Don't get owner for earringing

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
-  Ignore changelog.
- add some missing translations (German)
- corrected some spelling/ grammar
- #400
> FIX: Add missing translations

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Remove has marker parameter for respawn vehicle (@Vdauphin).
- title
> Add: Remove has marker parameter for respawn vehicle

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- Add: Clean up data fnc (@Vdauphin).
- title
> Add: Clean up data fnc

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- Add: Improve call_militia syntaxe (@Vdauphin).
- use the `btc_fnc_mil_send` function framework
> Add: Improve call_militia syntaxe

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- FIX: Static could be inside terrain or flip (@Vdauphin).
- Fix #726 
> FIX: Static could be inside terrain or flip

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- FIX: Civilian weapon isn't saved in the cache (@Vdauphin).
- title
> FIX: Civilian weapon isn't saved in the cache

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/deployRopes.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/destroyRopes.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hookFake.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hud.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hudLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/rsc.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- Add: Migrate lift system to a proper folder (@Vdauphin).
- title
> Add: Migrate lift system to a proper folder

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/cleanUp.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- Add: Migrate clean up fnc to city folder (@Vdauphin).
- title
- city object is local to server (need  v1.95.145741)
> Add: Migrate clean up fnc to city folder

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
- Add: Forest loadout (@Vdauphin).
- title
> Add: Forest loadout

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
- FIX: Towing for HEMTT flat (@Vdauphin).
- title
> FIX: Towing for HEMTT flat

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
- Add: Vehicle in vehicle for towing when available (@Vdauphin).
- title
> Add: Vehicle in vehicle for towing when available

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Description in capture officer mission (@Vdauphin).
- title
> FIX: Description in capture officer mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- Add: Filter object by parent in mission.sqf (@Vdauphin).
- title
> Add: Filter object by parent in mission.sqf 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> Add: Handcuff step for capture officer

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
> FIX: Remove unncessary format

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/checkLoop.sqf
- Add: ED-1 support for IED (@Vdauphin).
- title
> Add: ED-1 support for IED

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/typeOfPreview.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- Add: btc_fnc_typeOfPreview to easily show picture (@Vdauphin).
- title
> Add: btc_fnc_typeOfPreview

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/usefulCity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
> FIX: Can select null city

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout_composition.sqf
- Add: Contact asset to hideout (@Vdauphin).
- title
> Add: Contact asset to hideout

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getVehProperties.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/setVehProperties.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- Add: Set and get vehicle properties function (@Vdauphin).
- title
> Add: Set and get vehicle properties function

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Fix both Traditional & Simplified Chinese localization string "Delete".
- Fix Traditional & Simplified Chinese and Japanese localization string "Order".
> Fix: Wrong localized string in stringtable.xml

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- docs/InGame-documentation.md
- Ignore changlog.
- title
- https://github.com/Vdauphin/HeartsAndMinds/pull/758#issuecomment-523989892
- String show in Arma:
Language | Text
-- | --
original | Delete
english | Delete
czech | Odstranit
german | Löschen
russian | Удалить
polish | Usuń
italian | Elimina
spanish | Borrar
french | Supprimer
chinese | 刪除
japanese | 削除
korean | 삭제
portuguese | Deletar
chinesesimp | 删除
turkish | Sil
- @GoldJohnKing is it okay for you?
> Add: Use BI string for delete database

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
> FIX: missing mount FOB interaction

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Simplified Chinese Translation for Chemical Warfare
- Fix: a ":" in Simplified Chinese Translation
> Add: Simplified Chinese Translation for Chemical Warfare

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_leaflets.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/leaflets.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dismantle_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suiciderKilled.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/buildingchanged.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/explosives_defuse.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/treatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/hitch_points.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/unhook.sqf
- Put EH fnc to proper folder
- create tow folder
> Add: Improve change files structure

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add Simplified Chinese translation for Add-bodybag_subtask (@GoldJohnKing)
- https://github.com/Vdauphin/HeartsAndMinds/pull/766
> Add: Simplified Chinese translation for Add-bodybag_subtask

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Fix: improve Simplified Chinese translation on Chemical warfare (@GoldJohnKing)
- https://github.com/Vdauphin/HeartsAndMinds/pull/760
> Fix: improve Simplified Chinese translation on Chemical warfare

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Subtask body bag in side mission rescue pilot (@Vdauphin).
- title
> Add: Subtask place pilot in a body bag if he has been killed

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/trackItem.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- close #757
- need `1.96` because `deleted` event is triggered when player enter in a vehicle
> FIX: Missing fail condition in case of player disconnection

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Ignore changelog
- Improve several Simplified Chinese translation about FOB mounting and dismantle.
> Fix: improve Simplified Chinese translation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place.sqf
- FIX: Object spawn in floor while placing them (@Vdauphin).
- title
> FIX: Object spawn in floor while placing them

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> FIX: underwater_generator side in wrong btc_side_list

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> FIX: Wrong upper case

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Fix: %1 (instead of 1%) in Simplified Chinese translation.
#400
> Fix: %1 in Simplified Chinese translation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
> FIX: Missing picture for civtreatment

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/checkLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/electronicFailure.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/frequencies.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/updateDevice.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/tasktypes.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- README.md
- docs/Add-factions.md
- docs/Add-vehicle-or-boat-to-H&M-system.md
- docs/All-H&M-setting-and-tweak.md
- docs/Change-MAP-of-Hearts-and-Minds.md
- docs/For-developer-and-tester.md
- docs/InGame-documentation.md
- docs/Prevent-AI-from-spawning-near-the-base.md
- docs/faction_player.md
- Add: Spectrum device and EMP (@Vdauphin).
- title
> Add: Spectrum device and EMP

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/leaflets.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/get_class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/buildingchanged.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/eh_effects.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/explosives_defuse.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/remove_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/treatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/hitch_points.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/hook.sqf
> Add: Description to function

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/autosave.sqf
- Fix Autosave error, wrong parameter
> FIX: Autosave error

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/updateDevice.sqf
> FIX: Spectrum device not working after respawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- FIX: Missing splint in loadout (@Vdauphin).
- title
> FIX: Missing splint in loadout

- .github/release-drafter.yml
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- FIX: Missing private in populate.sqf (@Vdauphin).
- title
> FIX: Missing private in populate.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/disableDevice.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/updateDevice.sqf
> FIX: Spectrum device when getIn vehicle

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- FIX: Uniform is full when ACRE radio is added (@Vdauphin).
- title
> FIX: Uniform is full when ACRE radio is added

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/cachePicture.sqf
> FIX: Cache picture isn't show

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/cleanUp.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- docs/Add-factions.md
- docs/faction_player.md
- FIX: Lag on de activation city due to allMissionObjects (@Vdauphin).
- title
> FIX: Lag on de activation city due to allMissionObjects

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Now database saved under the master_daily branch will be compatible with the 1.20 when released
> FIX: Load dev db

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/damage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/damageLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/debug/message.sqf
> FIX: Tweak damage level for chemical

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- title
- before it show : 1.2.0 now 1.20.0 as intended
> FIX: Show properly the version number

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
- Add: Use new command `getMissionPath` (@Vdauphin).
- title
> Add: Use new command `getMissionPath`

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- docs/InGame-documentation.md
- Remove some documentation entry no more interesting (@Vdauphin).
- title
> Remove some documentation entry no more interesting

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/search_for_intel.sqf
- Add: Migrate progress bar from ACE to CBA (@Vdauphin).
- title
> Add: Migrate progress bar from ACE to CBA

- .github/release-drafter.yml
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- README.md
- FIX: ACEX Fortify objects not saved (@Vdauphin).
- title
- https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=57&tab=comments#comment-3396916
- Interaction looks overlap https://github.com/acemod/ACEX/issues/209
> FIX: ACEX Fortify objects not saved

- .github/release-drafter.yml
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- FIX: Now ace_medical_treatment_advancedBandages is not a bool (@Vdauphin).
- see https://github.com/acemod/ACE3/pull/7392
> FIX: Now ace_medical_treatment_advancedBandages is not a bool since ACE 3.13.1

- .github/release-drafter.yml
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hook.sqf
- FIX: The lifting support being destroyed during the hooking (@Vdauphin).
- title
> FIX: The lifting support being destroyed during the hooking

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/handleShower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- Add: Remove sleep in repair_wreck and delete (@Vdauphin).
- title
> Add: Remove sleep in repair_wreck and delete

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- docs/Add-factions.md
- docs/Add-vehicle-or-boat-to-H&M-system.md
- docs/faction_player.md
- FIX: Infinite loop when using 100% enemies in house mission parameter (@Vdauphin).
- title
> FIX: Infinite loop when using 100% enemies in house mission parameter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/add_eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/ammoUsage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/set_skill.sqf
- Add: Some header (@Vdauphin).
- title
> FIX: Some missing header

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Prevent redeploy when carrying object (@mrNo0b).
- title
> FIX: Prevent redeploy when carrying object

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Prevent mount FOB when carrying object (@Vdauphin).
- title
> FIX: Prevent mount FOB when carrying object

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- FIX: ACE Crew Served Weapons (CSW) not saved (@Vdauphin).
- Need: https://github.com/acemod/ACE3/pull/7635
- Need ACE 3.13.2 or later
> FIX: ACE Crew Served Weapons (CSW) not saved

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place.sqf
- FIX: Prevent using vehicles while carrying objects (@mrNo0b).
- title
- will release the object if player gets into vehicle
> FIX: Prevent using vehicles while carrying objects

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/trait.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/damage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
- Add: Loadout for drone and CBRN unit (@Vdauphin).
- title
> Add: Loadout for drone and CBRN

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/unhook.sqf
- Add: Remove spawn command from towing system (@Vdauphin).
- title
> Add: Remove spawn command from towing system

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
> FIX: Missing call of unit create for patrol units

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- Add: Custom location to map (@Vdauphin).
- title
> Add: Custom location to map

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: createLocation is local

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
> Add: Remove useless params

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- FIX: Use tow instead of lift for boat (@Vdauphin).
- title
> FIX: Use tow instead of lift for boat

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createUnit.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- Ignorechangelog.
- title
- replace https://github.com/Vdauphin/HeartsAndMinds/pull/864
> FIX: Delay vehicle creation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
> FIX: Missing injurer when cache destroyed

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_weapons.sqf
- Add: Hunter weapon to civilian (@Vdauphin).
- title
> Add: Hunter weapon to civilian

- .github/release-drafter.yml
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Avoid the use of drone for rescue pilot side mission (@Vdauphin).
- title
> FIX: Avoid the use of drone for rescue pilot side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
> FIX: Reputation change spamming

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: Missing task notification

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
- FIX: Missing crew for UAV loading from database and created at logistic point (@Vdauphin).
- title
> FIX: Missing crew for UAV loaded from database and created at logistic point

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/checkLoop.sqf
- Add: Ambush when IED explode (@Vdauphin).
- title
> Add: Ambush when IED explode

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/deleteLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/notify.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/removeRubbish.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/tasktypes.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- README.md
- Add: Reputation when removing IED (@Vdauphin).
- Add: Side mission remove rubbish (@Vdauphin).
- title
> Add: Reputation when removing IED and side mission remove rubbish

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
> FIX: btc_fnc_log_CuratorObjectPlaced_s no more exist

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/damageLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/showSubtitle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hookFake.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- Add: Improve syntax (@Vdauphin).
- title
> Add: Improve syntax

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- Add: Clean up interaction (@Vdauphin).
- title
> Add: Clean up interaction

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getVehProperties.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/setVehProperties.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- FIX: Supply vehicle property not persistent (@Vdauphin).
- title
> FIX: Supply vehicle property not persistent

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_fire.sqf
- FIX: Drone fire even dead for 5s (@Vdauphin).
- title
> FIX: Drone fire even dead for 5s

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- FIX: Respawn in altitude (@Vdauphin).
- title
> FIX: Respawn in altitude

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/refuelSource.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Can't refuel source truck (@Vdauphin).
- title
> FIX: Can't refuel source truck

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- Add: Improve population fnc (@Vdauphin).
- title
> Add: Improve population fnc

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/init_area.sqf
- Add: Rewrite IED init (@Vdauphin).
- title
> Add: Rewrite IED init

- docs/InGame-documentation.md
> FIX: Update documentation since add BI respawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
- Add: Simplify radius x/y to one radius (@Vdauphin).
- title
> Add: Simplify radius x/y

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
-FIX: Create FOB at the correct altitude (@Vdauphin).
- title
> FIX: Create FOB at the correct altitude

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- FIX: Virtual crew doesn't respawn for UAV (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/issues/738#issuecomment-645232401
> FIX: Virtual crew doesn't respawn for UAV

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: Size X Y doesn't existe anymore for btc_custom_loc

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/deleteLoop.sqf
- Add: btc_fnc_ied_deleteLoop support RHSUSAF M1132 Stryker
- Title
**Additional information:**
This could work with pr https://github.com/Vdauphin/HeartsAndMinds/pull/871.
> Add: btc_fnc_ied_deleteLoop support RHSUSAF M1132 Stryker

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Support of EDENinventory for btc_vehicles and btc_helo (@Vdauphin).
- title
- fix #909 
> Add: Support of EDENinventory for btc_vehicles and btc_helo

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_RHSUS_Altis.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_RHSUS_Tanoa.sqm
- Add: New units and vehicles in mission.sqm (@Vdauphin).
- title
~- [ ] remove curator event to mission.sqm~
> Add: New units and vehicles in mission.sqm

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- Fix: failed to spawn enemy vehicles
> Fix: failed to spawn enemy vehicles

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
> FIX: Some civilian mod does not inherite from civilian

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
> FIX: Remove Van_02_vehicle_base_F

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
> FIX: Waypoint are added endless

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/exec.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- Add: Delay IED, patrol and trafffic creation (@Vdauphin).
- title
- close #921 
> Add: Delay IED, patrol and trafffic creation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/ask_var.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- Add: Share btc_hideouts (@Vdauphin).
- title
> Add: Share btc_hideouts

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/deleteLoop.sqf
> FIX: Tag return reputation from IED remove

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- Add: Improve mission.sqf (@Vdauphin).
- title
> Add: Improve mission.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- FIX: Side mission spawn outside terrain (@Vdauphin).
- close https://github.com/Vdauphin/HeartsAndMinds/issues/929
> FIX: Side mission spawn outside terrain

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- Add: Improve activation.sqf syntax (@Vdauphin).
- title
> Add: Improve activation.sqf syntax

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
> FIX: Patrol and traffic not deleted when player too far

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/evacuate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- Add: Waypoint Timeout and completion radius persistant (@Vdauphin).
- title
- fix #935 
> Add: Waypoint Timeout and completion radius persistant

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- Add: Use CBA eh for chemical propagation (@Vdauphin).
- title
> Add: Use CBA eh for chemical propagation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
> FIX: AI get stuck by each other

- .github/release-drafter.yml
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- FIX Comment about btc_type_crewmen is a string not an array (@Vdauphin).
- title
> FIX: Comment about btc_type_crewmen is a string not an array

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
> FIX: Error of reputation notify

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
> FIX: isNull group error

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
> FIX: btc_fnc_mil_send must be unscheduled

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- Add: Clean up some AI behavior (@Vdauphin).
- title
> Add: Clean up some AI behavior

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
> FIX: City can be deactivate more than once

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_apply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/dlg.hpp
- Add: Support for multiple logistic point (@Vdauphin).
- title
> Add: Support for multiple logistic point

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- FIX: Apply careless and BLUE combat mode to civilian traffic (@Vdauphin).
- title
> FIX: Apply careless and BLUE combat mode to civilian traffic

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_give.sqf
- FIX: Civilian still moving even after STOP order (@Vdauphin).
- title
> FIX: Civilian still moving even after STOP order

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Respawn to leader of the group (@Vdauphin).
- title
> Add: Respawn to leader of the group

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- FIX: Syntax error when debug log is on in call militia (@Vdauphin).
- title
> FIX: Syntax error when debug log is on in call militia

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
> FIX: btc_fnc_fob_redeploy define twice

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
> FIX: Wrong respawn name

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- title
- fix https://github.com/Vdauphin/HeartsAndMinds/issues/936#issuecomment-671673280
> FIX: Wrong name for reputation notify

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- Add: Reputation change when helo are killed (@Vdauphin).
- title
> Add: Reputation change when helo are killed

- =BTC=co@30_Hearts_and_Minds.Altis/core/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/init.sqf
- Add: Use unscheduled environment for main init.sqf (@Vdauphin).
- title
- way fasssteeerrr
- before 30.0156s after 5.70703s with 20 shit mods
> Add: Use unscheduled environment for main init.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/initArea.sqf
> FIX: No road connected error

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: Missing documentation menu

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
> FIX: Debug view by waiting for the display

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- ACE handle better Killed EH see https://github.com/acemod/ACE3/pull/7561
- BI Killed is fired twice see https://feedback.bistudio.com/T149510
> FIX: Don't use BI EH because it fired twice

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- FIX: Make sure convoy side mission don't select marine (@Vdauphin).
- title
> FIX: Make sure convoy side mission don't select marine

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- Ignore change (@Vdauphin).
- title
> FIX: Convoy mission stuck due to empty path array

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
> FIX: Remove useless getvariable tags

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> FIX: Weapon on ammo cache

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/roof.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_staticOnRoof.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Static weapon on roof (@Vdauphin).
- title
> Add: Static weapon on roof

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- FIX: Cache spawn under water for building above water (@Vdauphin).
- title
> FIX: Cache spawn under water for building above water

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/eh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/initArea.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Gratify sentence (@Vdauphin).
- title
> Add: Grafity sentence

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- Add: Cache type is persistent (@Vdauphin).
- title
> Add: Cache type is persistent

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- Add: Remove pointer for array loaded from db (@Vdauphin).
- title
> Add: Remove pointer for array loaded from db

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/delete.sqf
> FIX: Player tags are not deleted from database

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/typeOf.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_staticOnRoof.sqf
> FIX: Avoid static spawn on roof for ruin, church and chapel

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/exec.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/initArea.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/initArea.sqf
- title
- https://github.com/Vdauphin/HeartsAndMinds/issues/921
> FIX: Split tag and IED init area and creation to reduce freeze on first activation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
> FIX: Use direct call for btc_fnc_mil_send

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
> FIX: Rename fnc btc_fnc_cache_hd_cache

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
> FIX: Units spawned around cache spawn infinitly between server restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/add_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
> FIX: Vehicle sended can blow up on city reactivation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout_composition.sqf
> FIX: Camonet sometimes fall for hideout due to collision

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- title
- spectrum should not work properly also
> FIX: Player wasn't contaminated by chemical agent

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/respawn.sqf
> FIX: Use instigator to find who killed/damage the unit

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- FIX: Military patrol can spawn inside rock (@Vdauphin).
- title
- Fix #1022 
> FIX: Military patrol can spawn inside rock

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/checkLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/fired_near.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
> FIX: IED boom doesn't call militia in some cases

- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Enoch.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Tanoa.sqm
> FIX: Missing sharp shooter in sqm

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
> FIX: Blacktemplars website is no more really related to Hearts and Minds

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
> FIX: Cancel convoy side mission when no path is found after 10s

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
> FIX: Can't tow over bridge

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
> FIX: Missing city parameter for civilians

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
> FIX: Can't remove IED wreck on dedicated server

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/deleteLoop.sqf
> FIX: Player name not display when cleaning IED wreck

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
> FIX: Convoy side mission start before the game start

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- FIX: Some building have only one position (@Vdauphin).
- title
> FIX: Some building have only one position

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/deleteLoop.sqf
- title
- drive nemmera above dead body return reputation
> FIX: Nemmera delete blood and return reputation

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/droneLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suiciderLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_activeLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- FIX: Detect player type accordingly to player side (@Vdauphin).
- title
- fix #1048 
> FIX: Detect player type accordingly to player side

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
- https://github.com/Vdauphin/HeartsAndMinds/discussions/1046
> FIX: Missing some location type

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- FIX: Multiple ViV (@Vdauphin).
- title
> FIX: Multiple ViV

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hd.sqf
- FIX: Error from agent returning an array instead of string in handledamage event (@Vdauphin).
- title
- For unknow reason the handledamage event return an array of position instead of a string _part for agent created by calculatePath
- [armaserver_1614473880.zip](https://github.com/Vdauphin/HeartsAndMinds/files/6056659/armaserver_1614473880.zip)
Output result of _this from the handledamage event: line 12941 time 1:20:09
````sqf
1:20:09 (0:00:00) fnc\rep\hd - REP HD = [Agent 0xe3315000,[[6450.78,3677.34,213.271],[6449.22,3678.91,213.271],[6444.53,3683.59,
1:20:09 213.271],[6435.16,3683.59,213.233],[6434.64,3683.53,213.196],[6418.23,3695.78,213.271],[6403.3,3709.91,213.67],[6386.89,
1:20:09 …
```
> FIX: Error from agent returning an array instead of string in handledamage event

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- Add: Trigger are created locally (@Vdauphin).
- title
> Add: Trigger are created locally

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hookFake.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/setCargo.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- FIX: Backpacks are not saved in cargo vehicle/box (@Vdauphin).
- title
> FIX: Backpacks are not saved in cargo vehicle/box

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/evacuate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/trackItem.sqf
- Add: Use new command syntax `units side` (@Vdauphin).
- title
> Add: Use new command syntax `units side`

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/respawn.sqf
- Add: Use unitIsUAV command (@Vdauphin).
- title
> Add: Use unitIsUAV command

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: French stringtable Le partie to la partie (@Vdauphin).
- title
- #400 
> FIX: French stringtable Le partie to la partie

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- FIX: findEmptyPosition not preloaded (@Vdauphin).
- title
> FIX: findEmptyPosition not preloaded

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/headless.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- Add: Remove useless parenthesis (@Vdauphin).
- title
> Add: Remove useless parenthesis

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/init.sqf
- Add: compileScript as alias of compile preprocessFileLineNumbers (@Vdauphin).
- title
> Add: compileScript as alias of compile preprocessFileLineNumbers

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Migrate hideout fnc to a specific folder (@Vdauphin).
- title
> Add: Migrate hideout fnc to a specific folder

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- Add: Rewrite create group fnc (@Vdauphin).
- title
> Add: Rewrite create group fnc

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- FIX: Only change position for city in deep water (@Vdauphin).
- title
> FIX: Only change position for city in deep water

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hookFake.sqf
- FIX: Wreck lifted clip with the terrain when not drop above it (@Vdauphin).
- title
> FIX: Wreck lifted clip with the terrain when not drop above it

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- FIX: City with a lot of house can be empty (@Vdauphin).
- https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=67&tab=comments#comment-3434685
> FIX: City with a lot of house can be empty

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- FIX: Multiple charges trigger multiple hideout destruction (@Vdauphin).
- title
> FIX: Multiple charges trigger multiple hideout destruction 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- FIX: Preload city for findEmptyPosition (@Vdauphin).
- title
> FIX: Preload city for findEmptyPosition

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- FIX: Object in container are not loaded after db load (@Vdauphin).
- title
> FIX: Objects in container are not loaded after db load

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hookFake.sqf
- FIX: Lifted big objects can flip due to weird physic (@Vdauphin).
- title
> FIX: Lifted big objects can flip due too weird physic

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeBreak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Towing by using previous behavior because arma physic too weird (@Vdauphin).
- title
- #400 
> FIX: Towing by using previous behavior because arma physic too weird

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
- FIX: You can tow from everywhere (@Vdauphin).
- title
> FIX: You can tow from everywhere

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Selectable reputation notification level change (@Vdauphin).
- title
> Add: Selectable reputation notification level change

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
> FIX: City door are not locked when game has been saved

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_apply.sqf
> FIX: Wrong format for empty inventory

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/xeh_PreInit_EH.hpp
> FIX: Missing compileScript

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/cleanUp.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/debug/units.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createAgent.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createUnit.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/exec.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- Add: Rename variable `btc_delay_createUnit` to `btc_delay_time` (@Vdauphin).
- title
- it is more understandable
> Add: Rename variable `btc_delay_createUnit` to `btc_delay_time`

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
> FIX: Wrong fonction name

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/usefulCity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/removeRubbish.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
- Add: Side fnc update for better readability (@Vdauphin).
- title
> Add: Side fnc update for better readability

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: City occupation is now deterministic (@Vdauphin).
- title.
- #400 
0%
50%
100%
> Add: City occupation is now deterministic

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/pandemic.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- README.md
- Add: Side mission with contaminated villager (@Vdauphin).
- title
- #400
> Add: Side mission with contaminated villager

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
- FIX: Others hideout don't capture city in some cases (@Vdauphin).
- title
> FIX: Others hideout don't capture city in some cases

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- Add: Improve syntaxe of hideout capture system (@Vdauphin).
- title
> Add: Improve syntaxe of hideout capture system

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Can start mission with 0 hideout, pure insurgency game mode (@Vdauphin).
- title
> Add: Can start mission with 0 hideout, pure insurgency game mode

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- FIX: Trigger not deleted when side capture officier fail (@Vdauphin).
- title
> FIX: Trigger not deleted when side capture officier fail

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- Add: Patrol Civi and mil should more patrol on city road (@Vdauphin).
- title
- They should fight less wall now...
> Add: Patrol Civi and mil should more patrol on city road

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- Add: Avoid merge conflict between master and master daily (@Vdauphin).
- title
> Add: Avoid merge conflict between master and master daily

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/addRespawn.sqf
- Add: Clean up killed event bug since BI fix it (@Vdauphin).
- title
- see https://feedback.bistudio.com/T149510
> Add: Clean up killed event bug since BI fix it

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/add_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
- Add: Rewrite waypoint system (@Vdauphin).
- title
- fix variable no more define
- add better namaing waypoint, migrate 0 to "HOUSE", 1 to "PATROL" and 2 to "SENTRY"
> Add: Rewrite waypoint system

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Chinesesimp translation for #1144 (@GoldJohnKing).
- #400
> Add: Chinesesimp translation for #1144

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/init.sqf
> FIX: Flag interaction is shown twice

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- FIX: Loaded UAV in ACE cargo don't have crew (@Vdauphin).
- saw after copy and paste container with UAV
> FIX: Loaded UAV in ACE cargo don't have crew

- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/cachePicture.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- Add: Diary icon (@Vdauphin).
- title
> Add: Diary icon

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/ehDetector.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Direct call function in events (@Vdauphin).
- title
> Add: Direct call function in events

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/checkArea.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/checkLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/effect_blurEffect.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/intro.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/pandemic.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/checkLoop.sqf
- Add: General clean up and improved debug (@Vdauphin).
- title
> Add: General clean up and improved debug

- =BTC=co@30_Hearts_and_Minds.Altis/mission__Enoch.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Tanoa.sqm
> FIX: Use btc_veh_fnc_addVehFromSQM for vehicles

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createAgent.sqf
- FIX: Animals walk always in the same direction (@Vdauphin).
- title
- due to this https://feedback.bistudio.com/T155634
> FIX: Animals walk always in the same direction

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Tweak radius of detection for side mission rescue pilot (@Vdauphin).
- title
> FIX: Tweak radius of detection for side mission rescue pilot

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- FIX: Civilian/traffic stopped by players don't move at all (@Vdauphin).
- title
> FIX: Civilian/traffic stopped by players don't move at all

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
> FIX: Waypoints for patrol/traffic on road are in the sky

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/flag/int.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/init.sqf
- Add: btc_flag_fnc_int (@Vdauphin).
- title
> Add: `btc_flag_fnc_int`

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- FIX: Drone have small radius of patrol (@Vdauphin).
- title
> FIX: Drone have small radius of patrol

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- FIX: Don't use hideout position to show side mission position (@Vdauphin).
- title
> FIX: Don't use hideout position to show side mission position

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
> FIX: Main task is show in map corner

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Enoch.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Tanoa.sqm
- Add: Remove bigShower variable (@Vdauphin).
- title
> Add: Remove bigShower variable

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- Add: Remove the fix from A3 2.06 for towing (@Vdauphin).
- title
> Add: Remove the fix from A3 2.06 for towing

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/setBodyBag.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/playerConnected.sqf
- Add: Migrate code in body and respawn events to a proper fnc (@Vdauphin).
- title
> Add: Migrate code in body and respawn events to a proper fnc

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/trait.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_markerTextLocal.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/typeOf.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- Add: General code improvements (@Vdauphin).
- title
> Add: General code improvements

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Disable the use of teleporte interaction while carrying objects with ACE (@Vdauphin).
- title
> FIX: Disable the use of teleporte interaction while carrying objects with ACE

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/dogtagGet.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/dogtagSet.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/setBodyBag.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/moveOut.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/addRespawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/respawn.sqf
> FIX: Dead body get deleted when wreck repair/helo respawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create_attachto.sqf
- FIX: Error Warning Message: No entry 'bin\config.bin/CfgWeapons.optic_Hamr_F' (@Vdauphin).
- title
-  [x] blow a cache just in case
> FIX: Error Warning Message: No entry 'bin\config.bin/CfgWeapons.optic_Hamr_F'

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/int.sqf
- FIX: Disable hook interaction on dead vehicle (@Vdauphin).
- title
> FIX: Disable hook interaction on dead vehicle

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
> FIX: Handle the case when player send order from vehicle

- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
> FIX: Can spectate AI

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/intro.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Show the number of days since mission start (@Vdauphin).
- title
- #400
> Add: Show the number of days since mission start

- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
> FIX: Interpret fall from the sky

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- FIX: Increase the range for unit spawn coefficient (@Vdauphin).
- title
> FIX: Increase the range for unit spawn coefficient

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/killed.sqf
- ignore
- title
- https://github.com/acemod/ACE3/pull/8734
> FIX: No reputation change if ACE detonateAfterCookoff false

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- FIX: Most of the time cache are outside city (@Vdauphin).
- title
> FIX: Most of the time cache are outside city

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/createMarker.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/dogtagGet.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/create_composition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/deleteEntities.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createAgent.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/waitAndExecute.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/door/get.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/deleteLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/has_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/search_for_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_give.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/shortcuts.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/terminal.sqf
> FIX: Update fix missing headers

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/ammoUsage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/road_direction.sqf
- FIX: Some road have no direction (@Vdauphin).
- title
> FIX: Some road have no direction

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
> FIX: btc_bigShower doesn't existe anymore

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf
> FIX: Improve performance of chem fnc checkloop with big array

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Enoch.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission__Tanoa.sqm
- FIX: Can't use multiple curator (@Vdauphin).
- title
> FIX: Can't use multiple curator

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/initArea.sqf
- FIX: IED and tag number consistency with city status (@Vdauphin).
- title
> FIX: IED and tag number consistency with city status

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/getHouses.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/roof.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/door/lock.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/createIntels.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_staticOnRoof.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- FIX: Static don't spawn in city without entrerable buildings (@Vdauphin).
- title
- First use entrerable building and then not entrerable
> FIX: Static don't spawn in city without entrerable buildings

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/pandemic.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/removeRubbish.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
- FIX: StrongpointArea could be choose for side (@Vdauphin).
- title
> FIX: StrongpointArea could be choose for side

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
> FIX: Side rescue give free reputation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- FIX: Side mission checkpoint error due to low number of road (@Vdauphin).
- title
> FIX: Side mission checkpoint error due to low number of road

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- FIX: Side mission civtreatment error when no road around a city (@Vdauphin ).
- title
> FIX: Side mission civtreatment error when no road around a city

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- FIX: City name and name marker were overlapping in debug (@Vdauphin).
- title
> FIX: City name and name marker were overlapping in debug

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Advise when the vehicle is not align with the towing vehicle (@Vdauphin).
- title
> FIX: Advise when the vehicle is not align with the towing vehicle

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/damage.sqf
> FIX: Chemical protection tweak for uniform

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
> Add: Switch param btc_p_respawn_arsenal default on

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- Add: ACE flags support (@Vdauphin).
- title
- need https://github.com/acemod/ACE3/pull/8696
> Add: ACE flags support

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
> FIX: Free reputation given when side mission repair is canceled

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- ignore
- title
- https://feedback.bistudio.com/T162941
> FIX: Event suppressed not fired when civi are local to headless

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
> FIX: Loadout generated were wrong for `ace_arsenal_fnc_verifyLoadout`

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: German Translation for new strings (@Pictureclass).
- Add german translations for new strings.
> FIX: Missing German Translation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- FIX: Delay the drone suicider and waypoint creation (@Vdauphin).
- title
> FIX: Delay the drone suicider and waypoint creation

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Missing Czech translation (@MJVEVERUSKA).
- Translation into Czech
- Tested on the server
- Everything OK
> FIX: Missing Czech translation 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
- FIX: Autoloadout support of new CUP map 2020 (@Vdauphin).
- title
> FIX: Autoloadout support of new CUP map 2020

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/flag/deploy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Only team leader can use flag (@Vdauphin).
- title
- #400
> Add: Only team leader can use flag

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/deployRopes.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hook.sqf
> FIX: Lift not working

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createAgent.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createUnit.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/exec.sqf
- Add: Delay global variable in mission.sqf (@Vdauphin).
- title
> Add: Delay global variable in mission.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- FIX: Error when no vehicles in entities layer (@Vdauphin).
- title
> FIX: Error when no vehicles in entities layer

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/addTicket.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/playerConnected.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/screen.sqf
- Add: Log to follow player's ticket value (@Vdauphin ).
- title
> Add: Log to follow player's ticket value

- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- FIX: Remove Spectator view (@Vdauphin).
- title
- Player get stuck with the view from his dead body
> FIX: Remove Spectator view

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/ammoUsage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/trait.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/weaponsfilter.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/ammoUsage.sqf
- Add: Remove parent check for arsenal filter (@Vdauphin).
- title
> Add: Remove parent check for arsenal filter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- Add: Clean up db save (@Vdauphin).
- title
> Add: Clean up db save

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Remove non latin characters from tag string (@Vdauphin).
- title
- #400
> FIX: Remove non latin characters from tag string

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Use side as key for respawn hashMap (@Vdauphin).
- title
> Add: Use side as key for respawn hashMap

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
- FIX: Taxi syntax error (@Vdauphin).
- title
> FIX: Taxi syntax error

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/inventoryGet.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/inventoryRestore.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/inventoryRestore.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FAdd: Restore default inventory of box or vehicles (@Vdauphin).
- title
-  #400
> Add: Restore default inventory of box or vehicles

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/typeOf.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/buildingchanged.sqf
- FIX: Now wall and fence trigger rep malus since A3 2.10 (@Vdauphin).
- title
- Avoid the malus for fence and wall
> FIX: Now wall and fence trigger rep malus since A3 2.10

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/eh.sqf
- Add: Tag on vehicle persist (@Vdauphin).
- title
> Add: Tag on vehicle persist

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/checkArea.sqf
- FIX: Can't spawn objects at logistic point (@Vdauphin).
- title
> FIX: Can't spawn objects at logistic point

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/buildingchanged.sqf
- FIX: Remove furniture and items from reputation malus (@Vdauphin).
- title
> FIX: Remove furniture and items from reputation malus

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/get.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/setBodyBag.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- FIX: Player's dead body disappear when player disconnect from the respawn screen (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/discussions/1417
> FIX: Player's dead body disappear when player disconnect from the respawn screen

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/get.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/setBodyBag.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/player.sqf
- FIX: Dead body marker still visible when disable (@Vdauphin).
- title
> FIX: Dead body marker still visible when disable 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/buildingchanged.sqf
- FIX: Avoid reputation lost for wall from CUP (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/discussions/1416
> FIX: Avoid reputation lost for wall from CUP

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/typeOf.sqf
- Add: Use build in hashMap from A3 for typeOf.sqf (@Vdauphin).
- title
> Add: Use build in hashMap from A3 for typeOf.sqf

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- Add: Change order of param mil house (@Vdauphin).
- title
> Add: Change order of param mil house

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/slot/deserializeState.sqf
> FIX: Saved wounds on player not restored on server without -autoinit

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/send.sqf
- Add: Tweak radius of spawn for in house units (@Vdauphin).
- title
~- [ ] reduce density of civi/enemy~
> Add: Tweak radius of spawn for in house units

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Mission parameters for prisoner tickets (@Vdauphin).
- title
> Add: Mission parameters for prisoner tickets

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/usefulCity.sqf
- FIX: Mission get stuck on map with isolated island (@Vdauphin).
- title
- Should fix 
```sqf
12:32:35 Error in expression <patrol_fnc_usefulCity);
private _pos = getPos _end_city;
if (_isBoat) then {
((>
12:32:35   Error position: <getPos _end_city;
if (_isBoat) then {
((>
12:32:35   Error getpos: Type Tableau, Objet,Location attendu
12:32:35 File mpmissions\Projet_Otan_17.dingor\core\fnc\patrol\init.sqf..., line 48
```
> FIX: Mission get stuck on map with isolated island

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/addTicket.sqf
> FIX: Hashmap tickets not updated when share

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/slot/serializeState.sqf
- FIX: Loadout error on saving player slot (@Vdauphin).
- title
> FIX: Loadout error on saving player slot

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/rearmSource.sqf
- FIX: Can't rearm a rearm source (@Vdauphin).
- title
- https://github.com/acemod/ACE3/blob/master/addons/rearm/functions/fnc_makeSource.sqf#L20
> FIX: Can't rearm a rearm source

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/rearmSource.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Rearm interaction translation (@Vdauphin).
- fix #1496 
- #400
> FIX: Rearm interaction translation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/slot/deserializeState_s.sqf
- FIX: Leader get teleported/loadout when a player in the same group join a game (@Vdauphin).
- title
- fix #1486 
> FIX: Leader get teleported/loadout/medical when a player in the same group join a game

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/init.sqf
- FIX: Huron Fuel/Ammo Containers resetting to full on server restarts (@Vdauphin).
- title
- fix #1502
> FIX: Huron Fuel/Ammo Containers resetting to full on server restarts

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/slot/serializeState.sqf
- FIX: Use CBA loadout for ACRE radio (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/pull/1407
- need ACRE 2.11
> FIX: Use CBA loadout for ACRE radio

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- FIX: Remove ;; (@Vdauphin).
- https://github.com/Vdauphin/HeartsAndMinds/discussions/1515
> FIX: Remove ;;

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- FIX: Vehicle loaded in vehicle disappear after server save and restart (@Vdauphin).
- title
> FIX: Vehicle loaded in vehicle disappear after server save and restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/propertiesSet.sqf
- FIX: Fuel source interaction appear twice (@Vdauphin).
- see title
> FIX: Fuel source interaction appear twice

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
delete when cancel
- FIX: Static not removed when side mission checkpoint cancelled (@Vdauphin).
- title
> FIX: Static not removed when side mission checkpoint cancelled

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- Add: btc_hideout_cityID in mission.sqf to manually define cities where hideout will spawn (@Vdauphin).
- title
> Add: btc_hideout_cityID in mission.sqf to manually define cities where hideout will spawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- FIX: Remove comment about turn off option for auto restart (@Vdauphin).
- title
> FIX: Remove comment about turn off option for auto restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/vehicle.sqf
- Add: Tag abandoned vehicles (@Vdauphin).
- title
> Add: Tag abandoned vehicles

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/spect/electronicFailure.sqf
- Add: EMP affect more electronic (@Vdauphin).
- title
> Add: EMP affect more electronic

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/foodGive.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/foodRemoved.sqf
- Add: Special variable for food (@Vdauphin).
- title
> Add: Special variable for food

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/define_mod.sqf
- FIX: Custom locations without side mission (@Vdauphin).
- title
- fix #1577
> FIX: Custom locations without side mission

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
FIX: Updating french translation
When merged this pull request will:
Update the translation
https://github.com/Vdauphin/HeartsAndMinds/issues/400
> FIX: Updating french translation

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/unit_killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/killed.sqf
- Add: Persistent explosive (@Vdauphin).
- title
> Add: Persistent explosive

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- FIX: Server Freeze on cache destruction (@Vdauphin).
- title
> FIX: Server Freeze on cache destruction

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place_key_down.sqf
- FIX: Damage after droping an object while running (@Vdauphin).
- title
- fix #1592 
> FIX: Damage after droping an object while running

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/propertiesSet.sqf
- FIX: Ream not available when ACE rearm is set unlimited (@Vdauphin).
- title
> FIX: Ream not available when ACE rearm is set unlimited 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/droneLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suiciderLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_activeLoop.sqf
- FIX: Bombers follow enemies (@Vdauphin).
- title
> FIX: Bombers follow enemies

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/addInteraction.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/addInteraction.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/add.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/addRespawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Respawn ACE interaction from outside base (@Vdauphin).
- Add: Respawn ACE interaction have a timeout of 1 min (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/pull/1596
> Add: Respawn ACE interaction from outside base

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Stringtable typo (@Vdauphin).
- title
> FIX: Stringtable typo

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/initArea.sqf
- FIX: IED overlap sometimes (@Vdauphin).
- title
> FIX: IED overlap sometimes

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- FIX: Side mission kill broken since ACE 3.18.0 (@Vdauphin).
- Title
> FIX: Side mission kill broken since ACE 3.18.0

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
- FIX: Side mission repair errors (@Vdauphin).
- title
> FIX: Side mission repair errors since ACE 3.18.0

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: Missing > in stringtable (@Vdauphin).
- title
> FIX: Missing > in stringtable

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/massacre.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Massacre side mission (@Vdauphin).
> Add: Massacre side mission

- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Fix : Deleting an </Original> tag in xml files (@Alfred-Neuman)
- Add :  French Translation (@Alfred-Neuman)
- Error in file stringtable.xml L340 ([/=BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml](https://github.com/Vdauphin/HeartsAndMinds/blob/9ef01f933d7cd49e981da06d19453d9da50938b7/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/stringtable.xml#L340)).
> FIX: Deleting a tag in xml files and update French translation
