Vdauphin/HeartsAndMinds

- =BTC=co@22_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
With Arma 3, BI add a new battlefield in Altis and Stratis, the Sea.
This pull request is proposing to extend the Heart and Mind to this new terrain.
- Add civ boat traffic.
- Add enemy boat patrol.
- Add enemy occupied marine.
The pull request is based on function use to spawn unit and vehicle but now when function select a water area, function choose the appropriate vehicule and unit type and add a WP link to this type. (https://github.com/Giallustio/HeartsAndMinds/issues/65)
> Add Heart and Swim !

- =BTC=co@22_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/civ/traffic_eh.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/unit_create.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/mil/unit_killed.sqf
- =BTC=co@22_Hearts_and_Minds.Altis/core/fnc/rep/killed.sqf
https://github.com/Giallustio/HeartsAndMinds/issues/81
Now btc_patrol_active or btc_civ_veh_active is an array of group. If all unit is dead in a group, group is grpNull.
If the array has grpNull element,  grpNull is remove from the array (https://github.com/Vdauphin/HeartsAndMinds/pull/80/files#diff-815b391aa171bb9c7461b29c0bee0a78R142) (https://github.com/Vdauphin/HeartsAndMinds/pull/80/files#diff-815b391aa171bb9c7461b29c0bee0a78R159)
After, the number of element in array is checked with btc_patrol_max (https://github.com/Vdauphin/HeartsAndMinds/pull/80/files#diff-815b391aa171bb9c7461b29c0bee0a78R159).
> FIX: btc_patrol_active and btc_civ_veh_active negative

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/init_area.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout_asked.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/troops.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_rinf.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
https://github.com/Giallustio/HeartsAndMinds/issues/93
Final test :
> Add : change select floor random count for selectRandom

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
trigger isn't spawning for city occupied with `dataunits > 0`
FIX: under some conditions, now city occupied are correctly set clear when all enemies are killed.
Final test :
> FIX: trigger spawn for occupied city with `dataunits > 0`

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
Object variable are not supported by profileNamespace
Now hideout info are for the same hideout before and after the server restart.
Final test :
> FIX: hideout marker after server restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
FIX: wrong rearm level at missing starting (now you can select it in mission parameter).
https://github.com/Vdauphin/HeartsAndMinds/issues/163
Final test :
> FIX: Rearm level selection in mission parameter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_add_WP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/traffic_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf
FIX: improve civil traffic behavior by choosing appropriate cities 
as before civ traffic spawn randomly around city activated by player.
Now wp for civ car is choose in the opposite of the city car spawn. 
Here is a demonstration :
if nothing found, normal search is used.
Final test :
> FIX: traffic wp choose opposite city from spawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/road_direction.sqf
Tanoa map has dirt trails which are not connected to anything and create error
Final test :
> FIX: dirt trails are not connected to anything

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
FIX: player can kill civilian without any reputation effect in some case.
when player comes back in a city, the player can kill or dmage civilian
without reputation effect
Final test :
> FIX: EH civilian

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
FIX: ACE3 warning when handcutoff is used in hostage side mission (link to ACE 3.7.0).
bug created by ACE3.7.0
https://github.com/Vdauphin/HeartsAndMinds/issues/217
Final test :
> FIX: warning of handcutoff due to locallity

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
FIX: ACE3 cook off animation disable for Side mission checkpoint. 
https://youtu.be/w4lMj7Q3DyE?t=57
Final test :
> FIX: disable cookoff for side checkpoint

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
it is an locality issue. now check locality and if not local move object to player ownership and waituntil for it
Final test :
> FIX: sometimes objects can't be lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
FIX: Sometimes objects can't be lift when fasteroping
Final test :
> FIX: sometimes objects can't be lift when fasteroping

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
FIX: C4 on suicider is not correctly display on dedicate.
Final test :
> FIX: C4 on suicider is not correctly display on dedicate

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
FIX: Time acceleration not working when loading from DataBase.
Reopened on the proper branch (https://github.com/Vdauphin/HeartsAndMinds/pull/285)
Final test :
> FIX: Time acceleration not working when loading

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
FIX: Date not being set up properly at mission start.
Couldn't find any references to setData/skipTime apart from loading, and the date selection never really worked for me (both dedicated & local). Added this to the init server, apparently setDate replicates nicely between clients and server.
Tested on a local server & dedicated, there's a bit of a 2-3s delay on a local server for the date to actually get changed.
Final test :
> FIX: Date not being set up properly at the start

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
FIX: RHS AA missile infantry is missing in config.
Some of the other configs have manpad infantry, we found that the RHS one spawns no manpad units. Not sure if it's for balance or not, so I figured I'd open this PR in case it's just an omission.
> FIX: RHS AA missile infantry to config

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
FIX: Pilot not being removed at the end of rescue mission.
Because we started feeling bad for shooting him after rescuing the poor sod. ;)
Final test :
> FIX: pilot not being removed at the end of rescue mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/end_mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/fail.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
FIX: Task notification appear to everybody when a player is connecting.
when a player is connecting, a notification to all player appear.
all task are not succeded in end mission state.
`btc_fnc_task_create/set_done/fail` are simpler know.
Final test :
> FIX: Task notification appear to everybody when a player is connecting

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
https://forums.bistudio.com/topic/165948-mp-btc-hearts-and-minds/?do=findComment&comment=3153926
In case of slow computer/server:
It is NOT a good idea to disable spawn for Helicopter because city will
not be activate until player get out. The AI will spawn directly infront
of players ...
A clever way could be to activate city when the pilot start to decrease
the helicopter speed for landing. So during the travel, no AI will spawn
until you start to apporch your landing zone.
Final test :
> Add: Optimize trigger detection

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
FIX: logistics point can't detect wreck when FRIES is equipped on helicopters.
https://github.com/Vdauphin/HeartsAndMinds/issues/305
Final test :
> FIX: logistics point can't detect werck when FRIES is equipped on helicopters

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/extended_InitPost_EH.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/garage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
https://github.com/Vdauphin/HeartsAndMinds/issues/224
It is not easy to add vehicles inside H&M system (wreck, logistic, database etc) when the game is running.
This will add the possibility to admin to create a vehicle directly with logistic box. It is available for Admin only (by default it will be desactivate).
Final test :
> Add: Garage for admin

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/buildingchanged.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- Add: Reputation malus when a building is damaged/destroyed (https://github.com/Vdauphin/HeartsAndMinds/pull/349).
Links to #288 
I don't have a dedicated server yet to test it on properly, but I'm looking mainly for review comments (although if someone can test it I won't say no to that!). As you can see in the code the idea is that the reputation malus can be applied in two ways: either by damaging a building or destroying. Technically destroying a building outright is better for your reputation then damaging and destroying, but in a way it makes sense - people don't really like you breaking their houses and then finishing them up later. ;)
The filter is applied on a prefix basis, so the first entry that matches the prefix will be the multiplier we take. I've set up basic multipliers …
> ADD: a reputation change whenever a building is destroyed

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/buildingchanged.sqf
https://github.com/Vdauphin/HeartsAndMinds/pull/349
@mtusnio When a building is damaged by player the building become a dynamic
(not a 1 - Primary but a 8 - TypeVehicle see here : https://community.bistudio.com/wiki/getObjectType). 
Before the filter discard those buildings.
Now player receive malus for building already damaged by player.
Final test :
> FIX: Rep malus not apply for building already damaged by player

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- FIX: Destroyed vehicle are not destroyed after server restart.
Final test :
> FIX: Destroyed vehicle are not destroyed after DB loading

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/getStructures.sqf
> Add: Detect military building

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
fix : https://forums.bistudio.com/forums/topic/165948-mp-btc-hearts-and-minds/?page=32&tab=comments#comment-3239466
https://community.bistudio.com/wiki/CfgAmmo_Config_Reference#aiAmmoUsageFlags
thanks @PabstMirror and @baermitumlaut
Final test :
this allow the detection of multiple aiAmmoUsageFlags like `"64 + 128 + 256"`
```
private _input = getnumber(configfile >> "CfgAmmo" >> _ammo >> "aiAmmoUsageFlags");
private _binString = [_input, 9] call ace_common_fnc_toBin;
private _bit256Set = (_binString select [(count _binString) - 9, 1]) == "1";
diag_log format ["BTC unit %1 ammo %2 input %3 %4", _unit,_ammo, _input,_bit256Set];
_bit256Set
```
This is not suitable because many weapons have 256 number. Anti Air weapons have only 256 number.
> FIX: Anti-Air infantry filter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- FIX: Vehicle explosion damage other objects around during database loading.
https://github.com/Vdauphin/HeartsAndMinds/pull/374
Need : ACE 3.11, https://github.com/acemod/ACE3/pull/5318
Final test :
> FIX: Vehicle explosion damage other objects around during database loading

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- fix a small script error in 'core/fnc/side/underwater_generator.sqf' (since https://github.com/Vdauphin/HeartsAndMinds/pull/383)
**excerpt from the RPT log**
```
14:42:31 Error in expression <te_group;
_pos = getPosASL _generator;
leader _group setPosASL [_pos select 0, >
14:42:31   Error position: <leader _group setPosASL [_pos select 0, >
14:42:31   Error leader: Typ Array, erwartet Objekt,Gruppe,Team member
14:42:31 File E:\Dokumente\Arma 3\mpmissions\ArmA-OtherProjects\HeartsAndMinds\=BTC=co@30_Hearts_and_Minds.Altis\core\fnc\side\underwater_generator.sqf, line 61
```
> FIX: Sidemission: destroy underwater generator Script error

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- remove the hideout information in final phase because it is not relevant for player. 
- Now, in final phase player have greater chance to have enemies position information because it replace the hideout information.
> FIX: Civilian no more give hideout information in final phase

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- fixed a small spacing error in the hint, when a FOB is created (see screenshots below)
- replaced `+` with `format` in /core/fnc/common/show_hint.sqf
- a small adjustment in stringtable.xml
OLD:
NEW:
> FIX: deploy FOB hint, missing space

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- Now other addon which do not follow Arma 3 standard have the civilian interaction (since https://github.com/Vdauphin/HeartsAndMinds/pull/270)
civi from Arma 3
civi from CUP Takistan
> FIX: Civilian H&M-interaction for mod

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- only a missing selection was added
- caused by #419 ([/core/def/param.hpp](https://github.com/Vdauphin/HeartsAndMinds/pull/419/files#diff-259f057b3d896120baeaa5846a6b013dL262))
> FIX: Missing basic value in rearm (param.hpp)

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- This remove `objNull` in `btc_vehicles` array which are not necessary to save in Data base.
> FIX: objNull in btc_vehicles

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- =BTC=co@30_Hearts_and_Minds.Altis/mission_Tanoa.sqm
- Since ACE 3.12, ACE module are deprecated (https://slack-files.com/T047TJFFL-F8CF8TVJR-e953dbf392)
- Since ACE 3.12, ACE setting is suppose to be choose in mission.sqm or on the fly by server admin or client (https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#how-to-use-already-existing-settings). So ACE setting entry in mission parameters is no more usefull. This remove ACE setting in mission parameters.
- OPTION must be use for H&M are now directly inside the mission.sqm
- Add debugconsole for admin ONLY
> FIX: Remove deprecated ACE module/mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/findposoutsiderock.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- check if enemy spawn inside rock by detecting the intersection of a line draw between the spawning position to the same position but with an offset of 100 meter.
- Check if the object intersecting the line is a rock.
- Search for a road or a safe poistion.
RTP : [Arma3_x64_2017-12-15_10-26-02.txt](https://github.com/Vdauphin/HeartsAndMinds/files/1562409/Arma3_x64_2017-12-15_10-26-02.txt)
> FIX: Enemy spawn inside rock

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- FIX: Remove everybody can disarm IED option in mission parameters.
- Remove everybody can disarm IED option in mission parameter
> FIX: Remove everybody can disarm IED option in mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- when side mission failed (because the convoy reach the city or fail to find a path), markers are not deleted.
> FIX: Markers are not deleted when side mission convoy/capture officer failed

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place_key_down.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add a new placing option: tilt
- Changed the handling of rotating and tilting of an object
- Use ACE3 Mousehint for release action
- Remove the old addAction entry
- Adaptation of stringtable.xml
- Changed handling of object status in database (save/load)
- use ```getPosWorld ``` and ```setPosWorld``` instead of ```getPosASL``` and ```setPosASL```
- added some comments
- handle ```setVectorDirAndUp``` on database save and load
> Add: Expand place options

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/functions.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/description.ext
- Move the CfgFunctions declaration from def/functions.hpp to description.ext
- Reason is that in case someone is editing the mission, to be able to add custom functions to it without having to edit a source file
n/a
> Keep CfgFunctions in description.ext

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- Sometimes the engine of vehicles can't be turn on due to the spawn at 0,0,0 position
- the 0,0,0 position is underwater so the engine takes damage from the water a little and randomnly.
> FIX: Sometimes engine of vehicles can't be turn ON

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- Use simple objects instead of objects for city location
- use `private` and `params` commands.
- City location is no more visible/editable from Zeus.
> Add: Optimize city creation by using Simple objects

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud_loop.sqf
- When `_cargo_y = 0` the   `_hud_y`  was not define resulting an error : 
```
21:01:19 Error in expression <log str([_hud_x_1, _hud_y_1]);
_obj_img ctrlsetposition [_hud_x_1, _hud_y_1];
_o>
21:01:19   Error position: <ctrlsetposition [_hud_x_1, _hud_y_1];
_o>
21:01:19   Error Type Nombre,Pas un chiffre, Nombre attendu
```
> FIX: Syntax error from btc_fnc_lift_hud_loop

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- FIX: Use sling load cargo memory points when available.
- "rhsusf_M1237_M2_usarmy_d" can't be sling loading thanks to slingloadcargomemorypoints because ropes are not created. The `_ropes_check` variable store ropes created and is check after to be sure ropes are created.
> FIX: SlingLoadCargoMemoryPoints during lift

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Entry to the mission parameters to easily switch between BIS and/or ACE arsenal (@1kuemmel1).
- add an entry to the mission parameters, which allows the player (admin) to easily switch between the arsenal types (BIS/ACE/both)
- adds multiple options to switch (see screenshot below)
> Add: Arsenal type parameter

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- civilian orders are now in the following order : 1, 2, 3, 4 not 1, 4, 2, 3
> FIX: Civilian order are not in the correct order

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/place.sqf
- Since https://github.com/Vdauphin/HeartsAndMinds/pull/448 you can't fire after placing an object until you respawn.
- the `btc_fnc_log_place` was not removing the `ace_common_fnc_addActionEventHandler` so player can't use his left bottom mouse any more.
- clean up (https://github.com/Vdauphin/HeartsAndMinds/pull/448/files?diff=unified#r167425203)
> FIX: Can't fire after placing an object

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
- FIX: Remove weapons when cache is destroyed (@Vdauphin).
- `deleteVehicle` on weapons when cache is destroyed.
> FIX: Remove weapons when cache is destroyed

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- Add: Faster loading on player connection (@Vdauphin).
- Use `CBA_fnc_waitUntilAndExecute` instead of `waituntil` which need a scheduled environnement previously done with `spawn` (See https://ace3mod.com/wiki/development/arma-3-scheduler-and-our-practices.html).
> Add: CBA waitUntilAndExecute in initplayer

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/extended_PreInit_EH.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/init.sqf
- similar like #422 
- replace `preprocessFile ` with `preprocessFileLineNumbers`
- replace `waitUntil ` with `CBA_fnc_waitUntilAndExecute` (just in [init_server.sqf](https://github.com/1kuemmel1/HeartsAndMinds/blob/f38f450852bc0f6b561d7958c2586b64a7897d02/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/init_server.sqf#L20))
> Add: missing preprocessFileLineNumbers part2

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- FIX: Wrong color for debug markers after restart for saved game (@Vdauphin).
- Initalize the "marker" variable on city in debug mode.
> FIX: Debug marker have wrong color after restart for saved game

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- FIX: Animation fleeing when 'get down' and getweapons (@Vdauphin).
- Reset the animation state when player give order get down and civilian getweapons
- no more weird animation where the civilian stand up take a virtual gun then seat down
> FIX: Animation fleeing

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- clean up remove destroyed vehicles because wrong condition
- remove `count` and prefer `select`
> FIX: btc wreck deleted by clean_up function

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/debug/message.sqf
- search for world name when fnc folder not found
> FIX: Now btc_fnc_debug_message work outside fnc folder

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- ignore change log (@Vdauphin).
- FIX: Waypoints creation at [0,0,0]
- `cba_fnc_taskPatrol` can't create waypoints on `units _group = []` because it `call CBA_fnc_clearWaypoints` which create a waypoint at `getPosATL (leader _group)`. Because  there are no leader, a waypoint at [0,0,0] position is created.
> FIX: Waypoints creation at [0,0,0]

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- before create_croup generate at least 1 enemy at the beginning and then a second depending on the ratio.
- this new ratio fit more the new behavior
> FIX: Most patrol around city spawn with only one unit

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_leaflets.sqf
- FIX: Can't drop leaflets (@Vdauphin).
- H&M uses  https://community.bistudio.com/wiki/Arma_3_Leaflets#Mission_Usage
- For some reason the last update (tank DLC) remove the weapon (`"Bomb_Leaflets"`) on drone so player can't select leaflets.
- This fix force the drone to use leaflets (`selectWeaponTurret`).
- also fix this strange behavior discribed here: https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=41&tab=comments#comment-3295622
> FIX: Can't drop leaflets

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/ammoUsage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/data.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/class.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/ammoUsage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/class.sqf
- Add: Use config and aiAmmoUsageFlags to dertermine btc_types (@Vdauphin).
- Use config to determine if is uav
- Use `btc_fnc_mil_ammoUsage` for diver
> Add: Use config and aiAmmoUsageFlags to dertermine btc_types

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- FIX: Remove also weapon holder simulated (@Vdauphin).
- weapon holder simulated aren't clean up by the clean_up function
> FIX: weapon holdersimulated isn't clean up

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/garage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/clean_up.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/check_cap.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- Add: Unsheduled to deactivate city (@Vdauphin).
```sqf
[] spawn {
for "_i" from 1 to 10 do {
[str(_i)] remoteExec ["systemchat"];
[102] call btc_fnc_city_activate;
["desactive"] remoteExec ["systemchat"];
[102] call btc_fnc_city_de_activate;
sleep 1;
};
};
```
- This is a workaround to FIX dedicated server crash when CBA is deleting `group` until this is published https://github.com/CBATeam/CBA_A3/pull/940
- Also use unsheduled to deactivate city
> Add: Unsheduled to deactivate city

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- FIX: Floating hideouts (@Vdauphin).
- don't save the `z` axis as it is in the `btc_fnc_mil_create_hideout`
> FIX: When saved hideout are shifted along z

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: Remove DLC statics from logistic point menu (@Vdauphin).
- use a more accurate filter to select only static HMG, GMG and Titan.
> FIX: Remove DLC statics from logistic point menu

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_markerTextLocal.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/create.sqf
- syntaxe error: could be a string or a number
-  task create error in params
> FIX: Syntaxe error in params for set marker local and task create functions

- tools/sqf_validator.py
- FIX: remoteExec variant with "code"
> FIX: RemoteExec variant with "code" for SQF Validator

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/deleteEntities.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- Ignore changelog 
- The CBA_common_PFHhandles can be more than 9 999 999 long when the PFH is used too much.
- `[ count (CBA_common_PFHhandles select {_x isEqualType 0}), count CBA_common_PFHhandles]`
> FIX: btc_fnc_delete using too much CBA_fnc_addPerFrameHandler

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/checkLoop.sqf
- The CBA_common_PFHhandles can be more than 9 999 999 long when the PFH is used too much.
> FIX: btc_fnc_ied_check using too much CBA_fnc_addPerFrameHandler

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/fired_near.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- The CBA_common_PFHhandles can be more than 9 999 999 long when the PFH is used too much.
- Now add IED in a global variable and remove them when there are deleted/destroyed.
> FIX: btc_fnc_ied_fired_near use way too much CBA_fnc_addPerFrameHandler

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/droneLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suiciderLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_activeLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- The CBA_common_PFHhandles can be more than 9 999 999 long when the PFH is used too much.
> FIX: btc_fnc_ied_suicider/drone use way too much CBA_fnc_addPerFrameHandler

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- FIX: Plane crash when they spawn (@Vdauphin).
- setdir on plane make the velocity of then null so then just fall and crash on the ground
- fix #647 
> FIX: Plane crash when they spawn

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- FIX: ACE vehicles' parameters not saved in database or after repair wreck (@Vdauphin).
- now it save vehicles parameter like: medical vehicle, repair vehicle, fuelcargo, fuel nozzle position
- save in database and when repair werck
- does not include "cargo space" as it is handle by H&M for gameplay reason: https://github.com/Vdauphin/HeartsAndMinds/issues/644#issuecomment-471327590
- Close #644 
> FIX: ACE vehicles' parameters not saved

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Mission parameter to change probability of a city to be free (@Vdauphin).
-  Add: Mission parameter to change probability of a city to be free
> Add: Mission parameter to change probability of a city to be free

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_check.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hud_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
- FIX: Repair wreck detect ACE fastrope (@Vdauphin).
- This remove ACE fastroping things when searching for vehicles
- fix #646 
> FIX: Repair wreck detect ACE fastrope

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
- FIX: Helo crash instantly when respawned (@Vdauphin).
- Now helo respawn with the vector defined in mission.sqm 
- fix #653 
> FIX: Helo crash instantly when respawned

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: btc_player_side error when side mission cycle is activated (@Vdauphin).
- brodcast btc_player_side before btc_fnc_task_create is execute
- fix #657 
> FIX: btc_player_side error when side mission cycle is activated

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/give_intel.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/hideout.sqf
- FIX: btc_fnc_info_hideout take an object as parameter not an array (@Vdauphin).
- title
> FIX: btc_fnc_info_hideout take an object as parameter not an array

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/autosave.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Save game when on allplayers disconnected (@Vdauphin).
- title
- autosave game break player experience when it is done during combat. Create a lot of confusion. In game, this should be only done with the seft interaction by admin
- remove https://github.com/Vdauphin/HeartsAndMinds/pull/233
- remove request: https://github.com/Vdauphin/HeartsAndMinds/issues/220
> Add: Save game when all players disconnected

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf
- FIX: FIX: PlaySound3D, allah akbar sound doesn't trigger on my server since 1.92 (@Vdauphin).
- Since 1.92 playSound3D take a sound volume lower than 5
- https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=53&tab=comments#comment-3359025
> FIX: PlaySound3D, allah akbar sound doesn't trigger on my server

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- FIX: Convert ASL to ATL when over sea (@Vdauphin).
- building pos return ASL when position is over see
- prevent object spawning in objects when there are over sea
> FIX: Convert ASL to ATL when over sea

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
- FIX: Avoid Van_02_vehicle_base_F because BI fault (@Vdauphin).
- title
- https://feedback.bistudio.com/T129141
- fix #668
> FIX: Avoid Van_02_vehicle_base_F because BI fault

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/find_closecity.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- FIX: Some patrol can spawn in water (@Vdauphin).
- Don't select marine location to avoid swiming unit when calling call_militia
> FIX: Some patrol can spawn in water

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- FIX: Enemies don't spawn inside the city radius (@Vdauphin).
- title
- fixes #751
- with the add of the `_area`, even with a radius of 80m, the deactivation.sqf works as intended
- before fix, radius list sorted:
- Lythium:
[15,25,25,50,50,50,50,50,50,50,50,50,50,50,50,50,90,90,90,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,130,150,200,200,200,200,200,200,200,200,200,200,200,250,290,300,300,300,300,390,400,400,500,500,500]
- Altis:
[150,150,150,200,200,200,200,200,200,200,200,200,200,200,200,220,250,250,250,250,250,260.96,260.96,260.96,260.96,270.58,277.27,277.27,300,300,300,300,300,300,300,300,300,300,300,300,300,300,<null>,<null>,<null>,300,300,300,300,300,300,300,300,300,300,300,300,300,346.59,350,350,350,350,350, …
> FIX: Enemy doesn't spawn inside the city radius

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
- FIX: Can't sling load werck and some RHS vehicles (@Vdauphin).
- title
- `ropeCreate` return `objNull` instead of `nil` since 1.94
> FIX: RopeCreate fail return objtNull

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- FIX: FOB spawn twice when two player create a FOB (@Vdauphin).
- title
>  FIX: FOB spawn twice when two players create a FOB

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/eh_effects.sqf
- FIX: Wrong icon for deploying rope in ship (@Vdauphin).
- title
> FIX: Wrong icon for deploying rope in ship

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP_loop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- FIX: Lag on city activation (@Vdauphin).
- The addwaypoint command takes 17.21ms and the CBA fnc takes 17.35ms with -1 it is around 100µs
- Will takes advantage of this also https://github.com/CBATeam/CBA_A3/pull/1277
https://files.slack.com/files-pri/T04889UCE-FS6LSTBU3/image.png
> FIX: Lag on city activation

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/cleanUp.sqf
- FIX: Chemical damage lag when a lot of units are contaminated (@Vdauphin).
- title
> FIX: Chemical damage lag when a lot of units are contaminated

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Game crash while searching intel (@Vdauphin).
- title
> commy2:bomb:  6:35 PM
>Use execNextFrame. Probably something about creating displays and deleting displays from a ui script.
>pabstmirror  6:35 PM
>it shouldn't cause the crash, but a lot of times you want to execNextFrame
[Arma3_x64_2020-03-14_18-16-55.zip](https://github.com/Vdauphin/HeartsAndMinds/files/4333129/Arma3_x64_2020-03-14_18-16-55.zip)
> FIX: Game crash while searching intel

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/lift/hookFake.sqf
- FIX: Lift wreck flip (@Vdauphin).
- title
- Use a heavier object and bigger to avoid wreck flip during lift
> FIX: Lift wreck flip

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders_behaviour.sqf
- FIX: Prevent civilian to stand up if in vehicle after ordering civilian to get down (@mrNo0b) 
- title
- When ordering civilian to get down he will stand up if he is in vehicle, causing him to clip thru the car roof 
**Screenshot:**
> FIX: Prevent civilian to stand up if in vehicle after ordering civilian to get down

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- FIX: FOB respawn position can be empty (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/issues/738#issuecomment-613707410
**Screenshot**
Typical case where the issue appearing:
> FIX: FOB respawn position can be empty

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/show_hint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/autoRestart.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/autosave.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Auto restart/shutdown (@Vdauphin).
- title
**Screenshot:**
> Add: Auto restart/shutdown 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- FIX: Skip side mission mines if no safe position found (@Vdauphin).
- title
> FIX: Skip side mission mines if no safe position found

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: Double portable lamp cannot be removed at logistics point, its says: no object to remove found
I don't know if its the best way to solve this issue, I only tried to remove the double lamp, but it will probably allow deleting other lamps so maybe its not the desired behavior.
- Add `Lamps_base_F` class to the `btc_log_main_rc` class array
> FIX: Impossible to remove spawned "Land_PortableLight_double_F"

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- FIX: Remove persistence of objects created by chemical leak side mission (@Vdauphin).
- title
> FIX: Remove persistence of objects created by chemical leak side mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/treatment.sqf
- FIX: Avoid reputation up while checking civilian medical status (@Vdauphin).
- title
> FIX: Avoid reputation up while checking civilian medical status

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Voted admin can see the database self interaction menu, this edit need more testing
- Prevent voted admin from using the Database self interaction menu
> FIX: Voted admin can see the Database self interaction menu

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
- Add: Scatter hideouts around the map (@Vdauphin).
- title
Old behavior for 10 hiedouts:
New behavior for 10 hiedouts:
> Add: Scatter hideouts around the map

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/cache.sqf
- FIX: Undefined variable for fake info cache (@Vdauphin).
- title
> FIX: Undefined variable for fake info cache

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- FIX: FOB height not restored when loading saved game (@Vdauphin).
- title
- fix #899 
> FIX: FOB height not restored when loading saved game

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/killed.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/redeployCheck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Option to redeploy from FOB to base (@Vdauphin).
- Add: Separate BI respawn and H&M redeploy (@Vdauphin).
- title
- https://github.com/Vdauphin/HeartsAndMinds/issues/738
**Screenshot:**
> Add: Redeploy from FOB to base, separate BI Redeploy and H&M Redeploy

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Side rescue, pilot can join player group if an air vehicle fly above (@Vdauphin).
- title
> FIX: Side rescue, pilot can join player group if an air vehicle fly above

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
- FIX: Killed-event handler can run twice for the same entity in some cases (@Vdauphin).
- title
- https://github.com/acemod/ACE3/pull/7561
- https://feedback.bistudio.com/T149510 not fixed in 2.00, may be never
> FIX: Killed-event handler can run twice for the same entity in some cases

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- FIX: EMP side mission stuck if ammo cache destroyed by non-explosive ammo (@Vdauphin).
- title
- fix #975 
> FIX: EMP side mission stuck if ammo cache destroyed by non-explosive ammos

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/cleanUp.sqf
- FIX: Adjust weapon holder clean up distance to match the clean up distance of dead bodys.
- Weapons will not be cleared before the body. This leads to strange situations where the dead body is still there but the weapon/launcher disappears.
> FIX: Adjust weapon holder clean up distance to match the clean up distance of dead bodys

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
- FIX: ViV objects are saved twice (@Vdauphin).
- title
- since https://github.com/acemod/ACE3/pull/7984
> FIX: ViV objects are saved twice

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tag/eh.sqf
- This attribute tag to a specific city.
- Before when two city was overlaping, just on city store the tag. So each time the second city is activated, it create new tags.
> FIX: Number of tags grow when two cities overlapping

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/add_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_grenade.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/get_weapons.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/add_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createAgent.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_static.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_staticOnRoof.sqf
- Ignorechangelog
- title
- Each AI is attributed to a city so even when city overlap, each AI is saved to the correct city
> FIX: AI spawn indefinitely when city overlapping

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
- FIX: Multiple interpreter can ask multiple time a civilian (@Vdauphin).
- title
> FIX: Multiple interpreter can ask multiple time a civilian

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/set_clear.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_free_condition.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
(Use English only.)
- Add: Enemy will surrender when city becomes free (@GoldJohnKing).
- If enemy amount is less than (0, 1, 2, 3), city will becomes free and remaining enemies will surrender.
- If unit is a UAV, it will be destroyed immediately.
- If unit is inside vehicle, it will dismount then surrender.
- If unit is on foot, it will surrender.
- Also added `setTriggerInterval` to decrease trigger check interval (default 0.5s now 2s), it may slightly improve performance.
- I'm new on coding, and the code seems not that gentle than I thought, so this might need to be carefully reviewed.
**_TODO_**
> Add: Enemy will surrender when city becomes free

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/evacuate.sqf
- FIX: Leaflets dropped to civilians doesn't evacuate if chapel or church are not around (@Vdauphin).
- title
> FIX: Leaflets dropped to civilians doesn't evacuate if chapel or church are not around

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
- Add: Remove variable to disable ace cookoff (@Vdauphin).
- title
- no more needed since https://github.com/acemod/ACE3/pull/8122
> Add: Remove variable to disable ace cookoff

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ViV.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/ropeCreate.sqf
- FIX: Multiple ViV for vehicle using vanilla ViV system (@Vdauphin).
- title
- Use a bigger object fitting vehicle size but still fitting RHS vehicle transport
- fix misspelling already...
> FIX: Multiple ViV for vehicle using vanilla ViV system

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
- FIX: For server using -autoinit, objects in container are not loaded after restart (@Vdauphin).
- title
- Looks like the `CBA_fnc_execNextFrame` fail in `btc_fnc_db_loadCargo` only for server using `-autoinit`
- May be the first frame do not support  `CBA_fnc_execNextFrame` but for sure there is a different behavior between server started by player and server using -autonint to start the mission
> FIX: For server using -autoinit, objects in container are not loaded after restart

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
- FIX: Militia can spawn inside hideout when player is near (@Vdauphin).
- the variable `_hideout` is not define in this scope, we want `_x`. It is noticable that Arma doesn't complain of this undefine variable.
> FIX: Militia can spawn inside hideout when player is near it

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- FIX: btc_hideouts is undefine when no hideout (@Vdauphin).
- title
> FIX: btc_hideouts is undefine when no hideout

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- FIX: Cap the amount of enemy spawns for an assassination and hostage rescue mission (@Vdauphin).
- title
> FIX: Cap the amount of enemy spawns for an assassination and hostage rescue mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
- FIX: Unit spawn in side are not link to the city of activation (@Vdauphin).
- Peopllle are stupid enough to set player activation radius at 100m so when units created by side can appear at 100m if an other city have a caching radius overlapping the city of the side
> FIX: Unit spawn in side are not link to the city of activation

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/init.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/EMP.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/chemicalLeak.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
- Add: Change variable name for city radius (@Vdauphin).
- title
- Make the radius name varaible more understandable
- `radius` --> `cachingRadius`, ie all AI in this radius will be cached on city desactivation
- `btc_city_radius` --> `btc_city_radiusOffset`, offset added to the cachingRadius so AI don't spawn in front of people.
> Add: Change variable name for city radius

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- FIX: Now ammo charge of suicide bomber follow the orientation of pelvis (@Vdauphin).
- title
> FIX: Now ammo charge of suicide bomber follow the orientation of pelvis

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
> FIX: Error _wp_ratios is not define anymore

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Side rescue give you reputation even when this mission fail (@Vdauphin).
- title
> FIX: Side rescue give you reputation even when this mission fail

- =BTC=co@30_Hearts_and_Minds.Altis/mission.sqm
- Add: Use game logic to detect all pre-placed vehicles (@Zakant).
- Use a game logic, that is synced to the vehicles, instead of the vehicles init fields to add those to the btc vehicle system.
- Add a EDEN comment to explain the game logics behaviour, what should be synced and what not (usefull for "first-time editors").
**Note**
I tried to cleanup the mission.sqm as good as I could. However, probably because of different arma versions, there are some changes the editor introduced which I did not removed.
> Use game logic instead of vehicle init fields

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/drone_create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_create.sqf
- FIX: Waypoints for drone and suicider take 15ms (@Vdauphin).
- title
> FIX: Waypoints for drone and suicider take 15ms

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/inventoryGet.sqf
- ignore
- title
- Spectrum device have dummy magazine whitch create an error when picking from an inventory after a saving
> FIX: Some weapon have dummy magazine creating error by picking them from inventory

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/hideout/create.sqf
- FIX: Hideout may cook off and destroy the hideout ammo box (@Vdauphin).
- title
> FIX: Hideout may cook off and destroy the hideout ammo box

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
- FIX: Ensure only players trigger hideout destruction (@Vdauphin).
- title
> FIX: Ensure only players trigger hideout destruction

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- Add: Reduce the number of patrol and traffic generate on city activation (@Vdauphin).
- title
- This should avoid to reach too quickly the maximum of patrol and traffic
> Add: Reduce the number of patrol and traffic generate per city activation

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- FIX: Can't set number of hideout above 5 in mission parameters (@Vdauphin).
- title
- The default value is not present so we can't define value above 5 hideout
> FIX: Can't set number of hideout above 5 in mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/tow/check.sqf
- FIX: Towing say Not align when vehicles were align but too close to each other (@Vdauphin).
- title
> FIX: Towing say Not align when vehicles were align but too close to each other

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- FIX: Disable debug teleport when on respawn screen (@Vdauphin).
- title
> FIX: Disable debug teleport when on respawn screen

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/playerConnected.sqf
- FIX: Some player may not get tickets on heavy modded server (@Vdauphin).
- title
- Give enough time (20min) for player to connect on heavy moded server before it was 4min
> FIX: Some player may not get respawn tickets on heavy modded server

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/addTicket.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/respawn/playerConnected.sqf
- FIX: Player's ticket saved is wrong after processing a prisoner for player who never died (@Vdauphin).
- title
- When a player never die but get new tickets with prisoner, the value saved in `btc_respawn_tickets` was wrong because it was using the default value `0` and not the default `btc_p_respawn_ticketsAtStart`
Before fix
After fix
> FIX: Player's ticket saved is wrong after processing a prisoner for player who never died

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getHouses.sqf
- FIX: Static spawn on hideout's objects when no house is detected around (@Vdauphin).
- title
> FIX: Static spawn on hideout's objects when no house is detected around

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover_s.sqf
- FIX: Body bag marker stay after wreck repaired with dead body inside (@Vdauphin).
- title
> FIX: Body bag marker stay after wreck repaired with dead body inside

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_damage.sqf
- FIX: Side civilian need help only have hematoma since ACE 3.15.1 (@Vdauphin).
- title
- fix https://github.com/Vdauphin/HeartsAndMinds/issues/1424
> FIX: Side civilian need help only have hematoma since ACE 3.15.1

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/getHouses.sqf
- FIX: Civilian do not populate randomly cities (@Vdauphin).
- title
> FIX: Civilian do not populate randomly houses in city

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/body/bagRecover_s.sqf
- FIX: Player in respawn screen don't get their ticket (@Vdauphin).
- title
- `units` don't return player while dead for no reason
> FIX: Player in respawn screen don't get their ticket from prisoner

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
- Add: Increase the base number of civilian per type of city (@Vdauphin).
- title
- Keep the default value by putting 50% as default
> Add: Increase the base number of civilian per type of city

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf
- FIX: Chemical range of propagation decrease when more than one unit get contaminated (@Vdauphin).
- title
> FIX: Chemical range of propagation decrease when more than one unit get contaminated

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/garage.sqf
- FIX: Vehicle orientation is wrong when spawn with garage (@Vdauphin).
- title
> FIX: Vehicle orientation is wrong when spawn with garage 

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
> FIX: Player not teleported inside the last vehicle occupied after server restart if vehicle have moved

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Select the power of IED in mission parameters (@SOF-Ice).
- Since an update of ACE, the explosion of EEI produce several damages to the EOD. most of the time he died in few minutes.
- Thats why i propose you to choose between the standard and an an other EEI smaller. The smaller produce less damage which allows time to heal the EOD.
> Add: Select the power of IED in mission parameters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/rearmSource.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/refuelSource.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/add.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/addRespawn.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/propertiesGet.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/propertiesSet.sqf
- FIX: Max ACE EDEN option rearm and refuel not saved (@Vdauphin).
- title
- see https://github.com/Vdauphin/HeartsAndMinds/discussions/1471
> FIX: ACE EDEN option max rearm and refuel values not saved

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/changeWeather.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- Add: Possibility to create ACE interaction to change time and weather /!\ **_only for officers_** /!\ (@SOF-Ice, @TomDraal).
- Add Ace interaction on btc_gear_object
- Possibility to change time (day or night) and weather in game without using Zeus modules
- Add new containers and keys in stringtable for those script with french traduction
**Screenshot**
> Add: Set day time and change weather

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/slot/deserializeState.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/slot/serializeState.sqf
- Add: CBA Extended Loadouts (@Vdauphin).
~- [ ] wait for https://github.com/IDI-Systems/acre2/pull/1205 and remove :~ 
```sqf
if (["acre_api"] call ace_common_fnc_isModLoaded) then {
_loadout = [_loadout] call acre_api_fnc_filterUnitLoadout;
};
```
> Add: CBA Extended Loadouts

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/propagate.sqf
- FIX: Don't propagate chem on object declare has string (@Vdauphin).
- title
> FIX: Don't propagate chem on object declare has string

- =BTC=co@30_Hearts_and_Minds.Altis/core/init_player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
- FIX: Dynamic Groups Init creating players without groups (@mrschick).
- Change the Dynamic Groups Init on server and players to register pre-existing groups, as per the [documentation](https://community.bistudio.com/wiki/Arma_3:_Dynamic_Groups#Installation).
Our community uses a modified mission file in which the playable slots are already organized into fireteams and leadership elements, with pre-made loadouts.
Sometimes entering a slot would cause the group to not be registered and the player be somewhat desynced on the server, not being able to join a group or creating his own group, leading to related issues like not being able to open the UAV terminal or control Drones.
None yet.
> FIX: Dynamic Groups Init creating players without groups

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- Add: Compatibility with Restrict Markers (@mrschick).
- Append a custom suffix to the markers loaded from the DB at mission start, making the system compatible with [Restrict Markers - Bagigi Fork](https://steamcommunity.com/sharedfiles/filedetails/?id=3245243732).\
Without this change, markers loaded from the DB would immediately be processed (turned into local copies) by Restrict Markers and not be available anymore to JIP clients.\
With the change, loaded markers will remain global until modified or deleted.
> Add: Compatibility with Restrict Markers

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
- FIX: "Cached" Typo (@mrschick).
- FIX: Refactor Time/Weather Interaction Conditions (@mrschick).
- Fix typo: [Ammo] "Cached", used in "ammo cache destroyed" markers.
- Refactor change time/weather interaction conditions on the Arsenal Box. If the parent `env_menu` condition is not met, the children won't be shown, so they don't need to check again for `player getVariable ["side_mission", false]`.
> FIX: Minor Improvements

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/droneLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suiciderLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_activeLoop.sqf
- FIX: Suicide/Drone bomber compatibility with KJW_Imposters (@mrschick).
- Make Suicide/Drone Bombers ignore "captive" units of the player side in their search and activation conditions/loops, this will make that system compatible with [KJW_Imposters](https://steamcommunity.com/sharedfiles/filedetails/?id=2917554904), preventing covert units from being targeted.
> FIX: Suicide/Drone bomber compatibility with KJW_Imposters

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- Add: Side Mission Improvements (@mrschick).
- In the "Capture Officer in Convoy" Mission, fix the Officer not disembarking his vehicle once surrendered.\
Previously, if the officer's vehicle was not disabled (leading to him disembarking) before "surrendering" him, it would become almost impossible to get him out of the vehicle safely.\
Now, he will disembark by himself, regardless of vehicle health, before surrendering.
- In the "Rescue Heli Pilot" Mission, fix the Pilot being "found" immediately after mission creation.\
This was being caused by the pilot activating his own "found" trigger, which looks for units of the player side <20m from the pilot, being turned non-captive and then often being killed by nearby enemy units, before players had a …
> Add: Side Mission Improvements

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
- FIX: Backpacks with integrated Wirecutter can Break Doors (@mrschick).
- Allow Break Door interaction when carrying a vest or backpack defined with it, as per the ACE [wirecutter framework](https://ace3.acemod.org/wiki/framework/wirecutter-framework).\
Reuses the following condition check used within ACE:\
https://github.com/acemod/ACE3/blob/3728bc4b8b30bb65b52c9b38762061cbf0933b4f/addons/logistics_wirecutter/script_component.hpp#L90-L93
> FIX: Backpacks with integrated Wirecutter can Break Doors

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/door/break.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/search_for_intel.sqf
- FIX: Use ACE Progressbar for Interactions (@mrschick).
- Use the ACE ProgressBar instead of CBA ProgressBar on "Break Door" and "Search Intel" interactions.\
The ACE version is preferable since it allows CBA Keybinds to work while interacting, i.e: ACRE radio PTTs.
> FIX: Use ACE Progressbar for Interactions

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- FIX: Autosave after all players disconnect not  working always (@Vdauphin).
- `allPlayers` is not always updated when player disconnect from the server
- When checking, we need to remove it from the player list if still present
- fix https://github.com/Vdauphin/HeartsAndMinds/issues/1651
> FIX: Autosave after all players disconnect not  working always

- =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/create.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/chem/handleShower.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Hi,
I've made some changes in order to add some more advanced settings on the Chemical Warfare in H&M.
The idea is to enable chemical warfare and choose if the chemical side missions will spawn or not and also set a chance probability of having a chemical weapons cache or not.
- Add: Setting to toggle chemical side mission (@TomDraal).
- Add: Setting to change chemical weapon cache probability (@TomDraal).
- Allow the user to choose if he/she wants to have chemical side missions while chemical warfare is enabled
- Tweak the chance probability (%age) of having a chemical weapons cache
> Add: Setting to toggle chemical side mission and chemical weapon cache probability

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
- FIX: Wreck Fire killing Pilot in Rescue Mission (@mrschick)
- title
Since https://github.com/acemod/ACE3/pull/9962 wrecks are a source of fire, this was causing rescue missions to fail immediately due to the pilot being burned (since he is spawned next to the wreck).
Fixed by explicitly disabling destruction effects, which prevents ACE from adding a fire source to the wreck.
> FIX: Wreck Fire killing Pilot in Rescue Mission

- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
- =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
- FIX: Boat Patrols Spawning in Ponds (@mrschick)
- Prevent boats from spawning in shallow water of less than 2m depth. Would happen frequently on the Vietnam map I'm currently using, resulting in Vietcong patrol boats spawning in rice fields that are cut off from the surrounding rivers.
> FIX: Boat Patrols Spawning in Ponds
